import type { Language } from './i18n'

export type PageId = 'home' | 'about-us' | 'services' | 'fleet' | 'industries' | 'request-a-quote' | 'contact' | 'privacy-policy' | 'cookies' | 'terms' | 'careers' | 'news'

type Card = { title: string; text: string; icon?: string }
type PageContent = {
  hero: [string, string, string, string]
  heading?: [string, string, string]
  paragraphs?: string[]
  cards?: Card[]
  note?: string
}
type LocaleContent = {
  label: string
  nav: Record<string, string>
  common: Record<string, string>
  pages: Partial<Record<PageId, PageContent>>
  quote: {
    intro: string; fieldsTitle: string; formTitle: string; requiredNote: string; labels: Record<string, string>
    select: string; errors: Record<string, string>; loading: string; success: string; notConfigured: string; genericError: string
  }
  legal: Record<'privacy-policy' | 'cookies' | 'terms', { title: string; sections: Card[]; note: string }>
  careers: { emptyTitle: string; emptyText: string; button: string }
  news: { emptyTitle: string; emptyText: string }
  cta: { eyebrow: string; title: string; text: string; quote: string; contact: string }
  seo: Record<PageId, [string, string]>
}

export const siteCopy: Record<Language, LocaleContent> = {
  en: {
    label: 'English',
    nav: { home: 'Home', 'about-us': 'About Us', services: 'Services', fleet: 'Fleet', industries: 'Industries', contact: 'Contact', careers: 'Careers', news: 'News', quote: 'Request a Quote', privacy: 'Privacy', cookies: 'Cookies', terms: 'Terms', search: 'Search', language: 'Language' },
    common: { skip: 'Skip to content', menuOpen: 'Open menu', menuClose: 'Close menu', home: 'Trevola Logistics home', searchPlaceholder: 'Search services, pages and information', searchClose: 'Close search', searchEmpty: 'No matching pages found.', searchLabel: 'Search this website', breadcrumb: 'Home', footerText: 'International road freight, coordinated with care.', explore: 'Explore', contact: 'Contact', rights: 'All rights reserved.', backTop: 'Back to top', email: 'Email', phone: 'Phone', website: 'Website', license: 'Transport License', licenseNumber: 'No. 901091', whatsappLabel: 'Contact Trevola Logistics on WhatsApp', basedPortugal: 'Based in Portugal', connectedEurope: 'Connected across Europe', requestQuote: 'Request a Quote', discuss: 'Discuss your shipment', mapNote: 'Illustrative map · route availability subject to confirmation for each shipment', portugal: 'Portugal', europe: 'Europe' },
    pages: {
      'about-us': { hero: ['About Trevola', 'A road freight partner', 'built on coordination.', 'Clear communication and practical transport planning between Portugal and Europe.'], heading: ['A partner you can reach', 'Road freight,', 'made clearer.'], paragraphs: ['Trevola Logistics coordinates international road transport between Portugal and destinations across Europe.', 'We focus on the details that help a shipment move smoothly: understanding the load, agreeing the route and timing, and keeping communication clear while transport is coordinated.', 'Every request is different. Our role is to listen, identify suitable options and stay close to the details from collection through delivery.'], cards: [{ title: 'Understand the brief', text: 'We start with the cargo, origin, destination, timing and handling requirements.' }, { title: 'Coordinate the plan', text: 'We discuss suitable road transport options and confirm the details for the requested movement.' }, { title: 'Stay connected', text: 'We remain a clear point of contact while the shipment is being coordinated.' }] },
      services: { hero: ['Road Freight Services', 'The right solution', 'for every shipment.', 'Flexible road transport options shaped around your cargo, route and timing.'], heading: ['Road freight solutions', 'Transport shaped', 'around your cargo.'], paragraphs: ['Choose a service to start the conversation. Availability and final arrangements are confirmed for each shipment.'], cards: [{ icon: 'truck', title: 'Full Truck Load (FTL)', text: 'Dedicated vehicle capacity for full loads, planned around the route, cargo requirements and requested delivery window.' }, { icon: 'boxes', title: 'Less Than Truck Load (LTL)', text: 'Part-load and groupage options for shipments that do not require a full vehicle.' }, { icon: 'clock', title: 'Express Road Freight', text: 'Time-sensitive transport coordinated with clear communication and attention to agreed timings.' }, { icon: 'route', title: 'Dedicated Transport', text: 'A focused transport plan shaped around the specific needs of your shipment.' }, { icon: 'globe', title: 'European Road Freight', text: 'International road transport coordination between Portugal and selected European destinations.' }, { icon: 'shield', title: 'Logistics Coordination', text: 'A direct point of contact to coordinate the shipment from collection through delivery.' }] },
      fleet: { hero: ['Fleet & Network', 'Capacity that moves', 'your business forward.', 'Road transport coordinated to match the needs of each shipment.'], heading: ['Fleet & transport network', 'Flexible capacity.', 'One clear contact.'], paragraphs: ['Trevola coordinates road transport capacity to fit the shipment rather than relying on a one-size-fits-all solution.', 'Vehicle type, route, loading requirements and timing are discussed for each request. The available transport arrangement is confirmed before a shipment is booked.', 'Trevola Logistics is presented as a transport coordinator. Vehicle ownership is not claimed.'], cards: [{ title: 'Shipment profile', text: 'We review dimensions, weight, cargo type, collection point and delivery needs.' }, { title: 'Transport option', text: 'Suitable vehicle capacity and route options are discussed against the shipment requirements.' }, { title: 'Confirmed details', text: 'Timing and operational arrangements are confirmed with you before transport proceeds.' }] },
      industries: { hero: ['Industries We Serve', 'Transport shaped', 'around your sector.', 'A considered approach to cargo, route and timing across varied industries.'], heading: ['Industries We Serve', 'Road freight for', 'different demands.'], paragraphs: ['Every sector has its own transport considerations. We begin with the cargo, route and timing, then discuss a suitable road freight option.'], cards: [{ icon: 'car', title: 'Automotive', text: 'Components and goods moving through automotive supply chains.' }, { icon: 'wheat', title: 'Agriculture', text: 'Transport planning for agricultural products and materials.' }, { icon: 'industry', title: 'Industrial Equipment', text: 'Coordination for machinery, parts and industrial equipment.' }, { icon: 'cart', title: 'Retail', text: 'Goods movement for distribution, replenishment and stock planning.' }, { icon: 'food', title: 'Food & Beverage', text: 'Food and beverage cargo coordination based on shipment requirements.' }, { icon: 'package', title: 'E-commerce', text: 'Transport options for online retail goods and fulfilment flows.' }], note: 'These categories are examples of general cargo requirements. Special handling, regulated goods and equipment availability must be confirmed before booking.' },
      contact: { hero: ['Contact', 'Let’s start', 'a conversation.', 'Speak with Trevola Logistics about your road freight requirements.'], heading: ['Contact Trevola Logistics', 'Let’s talk about', 'your next shipment.'], paragraphs: ['Our team is available to discuss road transport between Portugal and European destinations.', 'Share your origin, destination, cargo details and preferred timing. We’ll help you understand the next steps and the information needed to prepare a request.'] },
    },
    quote: { intro: 'Share your cargo and route details. Our logistics team will have the information needed to discuss a suitable solution.', fieldsTitle: 'Tell us what you need to move', formTitle: 'Shipment details', requiredNote: 'Fields marked with * are required.', labels: { company: 'Company Name', contact: 'Contact Person', email: 'Email', phone: 'Phone Number', pickupCountry: 'Pickup Country', pickupCity: 'Pickup City', deliveryCountry: 'Delivery Country', deliveryCity: 'Delivery City', transport: 'Type of Transport', pallets: 'Number of Pallets', cargo: 'Cargo Description', weight: 'Weight (kg)', volume: 'Volume (m³)', loadingDate: 'Preferred Loading Date', additional: 'Additional Information' }, select: 'Select transport type', errors: { required: 'Please complete this field.', email: 'Enter a valid email address.', minimum: 'Enter a valid positive number.', date: 'Choose today or a future date.', wholeNumber: 'Enter a whole number.' }, loading: 'Sending request…', success: 'Thank you. Your quote request has been sent to Trevola Logistics.', notConfigured: 'Online quote submission is not configured yet. Nothing was sent. Please email info@trevolalogistics.com.', genericError: 'We could not send your request right now. Please try again or email info@trevolalogistics.com.' },
    legal: {
      'privacy-policy': { title: 'Privacy Policy', sections: [{ title: 'Who is responsible', text: 'This website is operated by Trevola Logistics, Lda. (Portuguese tax number, NIF: 516173812). For privacy questions, contact info@trevolalogistics.com.' }, { title: 'Information and purposes', text: 'When you submit a quote request, the form details (company and contact details, email, phone, route, cargo, weight/volume and requested date) are used to respond and prepare a possible quotation. The hosting provider may also process technical security logs.' }, { title: 'Legal basis and recipients', text: 'Quote enquiries are processed to take steps requested before entering a contract. Messages are sent to info@trevolalogistics.com using Resend and the company mailbox provided by Zoho. Vercel provides hosting and backend functions; Cloudflare provides DNS. Processing locations, subprocessors and safeguards for any international transfers still need to be confirmed.' }, { title: 'Retention and your rights', text: 'Personal data from quote requests that do not result in a contract is kept for one month after the request is closed. Customer personal data used to coordinate a shipment and applicant data is kept for one month after the service is completed or the application is closed. Accounting and tax documents subject to mandatory retention are kept for the period required by law. Depending on the applicable rules, you may request access, correction, deletion, restriction or object to processing, and may complain to the Portuguese Data Protection Authority (CNPD). Contact info@trevolalogistics.com to exercise a right.' }, { title: 'Updates', text: 'This draft must be reviewed against the actual legal entity, hosting, email provider, retention schedule and processing practices before publication. The date below should be updated after that review.' }], note: 'Draft for completion by the website operator · Last reviewed 9 October 2026' },
      cookies: { title: 'Cookie Policy', sections: [{ title: 'Current website storage', text: 'The current site does not load advertising or analytics tools. It stores your language choice in your browser’s local storage so the selected language can be remembered. This is a functional preference; it is not used for advertising or profiling.' }, { title: 'Essential technologies', text: 'The hosting platform may use technical mechanisms needed to deliver and secure the site. The operator should verify the hosting provider’s own storage and log practices before publication.' }, { title: 'Your choices', text: 'You can remove the saved language preference using your browser’s site-data controls. If optional analytics or marketing technologies are added later, this notice and the consent experience must be reviewed before they are enabled.' }, { title: 'Questions', text: 'For questions about this notice or the site’s storage practices, contact info@trevolalogistics.com.' }], note: 'This notice describes the current site code and must be checked against the final hosting setup.' },
      terms: { title: 'Terms & Conditions', sections: [{ title: 'Website information', text: 'This website provides general information about Trevola Logistics and its road transport coordination services. Content is not a binding offer or confirmation that a route, vehicle or date is available.' }, { title: 'Quotes and bookings', text: 'A request for a quote is an enquiry only. Transport scope, price, capacity, timing, handling requirements and contractual terms must be confirmed in writing before a booking is accepted.' }, { title: 'Accuracy and availability', text: 'Information and illustrative maps or images are provided for general guidance. Actual routes, service availability and operational arrangements are confirmed for each shipment.' }, { title: 'Intellectual property and contact', text: 'Website text, layout and Trevola Logistics brand materials may not be copied or reused without the relevant rights holder’s permission. For questions about these terms, contact info@trevolalogistics.com.' }, { title: 'Operator details and governing law', text: 'The website operator is Trevola Logistics, Lda. (Portuguese tax number, NIF: 516173812). The governing-law and jurisdiction details still need confirmation before these draft terms can be finalised.' }], note: 'Draft terms · Review and complete company and jurisdiction details before publication.' },
    },
    careers: { emptyTitle: 'No open positions right now', emptyText: 'We are not currently listing vacancies. If you would like to introduce yourself for future opportunities, contact our team by email.', button: 'Contact Trevola Logistics' },
    news: { emptyTitle: 'No updates published yet', emptyText: 'There are no news articles to show at the moment. Check back later for company and logistics updates.' },
    cta: { eyebrow: 'Ready to move forward?', title: 'Ready to Move Your Cargo?', text: 'Our logistics experts are ready to provide the best transport solution for your business.', quote: 'Request a Quote', contact: 'Contact Us' },
    seo: {
      home: ['Trevola Logistics | European Road Freight', 'International road freight between Portugal and European destinations, coordinated by Trevola Logistics.'],
      'about-us': ['About Us | Trevola Logistics', 'Meet Trevola Logistics, a Portugal-based partner for coordinated road freight across Europe.'],
      services: ['Road Freight Services | Trevola Logistics', 'Explore FTL, LTL, express and dedicated road transport coordination for European shipments.'],
      fleet: ['Fleet & Network | Trevola Logistics', 'Road transport capacity coordinated around shipment requirements, routes and timing.'],
      industries: ['Industries We Serve | Trevola Logistics', 'Road freight coordination for automotive, agriculture, retail, food and other industries.'],
      'request-a-quote': ['Request a Quote | Trevola Logistics', 'Share your route and cargo details to request a Trevola Logistics road freight quotation.'],
      contact: ['Contact | Trevola Logistics', 'Contact Trevola Logistics in Portugal about international road freight and shipment requirements.'],
      'privacy-policy': ['Privacy Policy | Trevola Logistics', 'How Trevola Logistics handles website and transport enquiry information.'],
      cookies: ['Cookie Policy | Trevola Logistics', 'Information about cookies and browser storage used by the Trevola Logistics website.'],
      terms: ['Terms & Conditions | Trevola Logistics', 'Website and enquiry terms for Trevola Logistics road transport coordination.'],
      careers: ['Careers | Trevola Logistics', 'Career opportunities and contact information for Trevola Logistics.'],
      news: ['News | Trevola Logistics', 'Company and logistics updates from Trevola Logistics.'],
    },
  },
  pt: {
    label: 'Português',
    nav: { home: 'Início', 'about-us': 'Sobre nós', services: 'Serviços', fleet: 'Rede', industries: 'Indústrias', contact: 'Contactos', careers: 'Carreiras', news: 'Notícias', quote: 'Pedir orçamento', privacy: 'Privacidade', cookies: 'Cookies', terms: 'Termos', search: 'Pesquisar', language: 'Idioma' },
    common: { skip: 'Saltar para o conteúdo', menuOpen: 'Abrir menu', menuClose: 'Fechar menu', home: 'Página inicial Trevola Logistics', searchPlaceholder: 'Pesquisar serviços, páginas e informações', searchClose: 'Fechar pesquisa', searchEmpty: 'Não foram encontradas páginas correspondentes.', searchLabel: 'Pesquisar neste website', breadcrumb: 'Início', footerText: 'Transporte rodoviário internacional, coordenado com cuidado.', explore: 'Explorar', contact: 'Contactos', rights: 'Todos os direitos reservados.', backTop: 'Voltar ao topo', email: 'Email', phone: 'Telefone', website: 'Website', license: 'Alvará Transitário', licenseNumber: 'Nº 901091', whatsappLabel: 'Contactar a Trevola Logistics pelo WhatsApp', basedPortugal: 'Sediados em Portugal', connectedEurope: 'Ligados a destinos europeus', requestQuote: 'Pedir orçamento', discuss: 'Fale sobre a sua expedição', mapNote: 'Mapa ilustrativo · disponibilidade sujeita a confirmação para cada expedição', portugal: 'Portugal', europe: 'Europa' },
    pages: {
      'about-us': { hero: ['Sobre a Trevola', 'Um parceiro de transporte', 'com coordenação cuidada.', 'Comunicação clara e planeamento rodoviário entre Portugal e a Europa.'], heading: ['Um parceiro próximo', 'Transporte rodoviário,', 'com clareza.'], paragraphs: ['A Trevola Logistics coordena transporte rodoviário internacional entre Portugal e destinos europeus.', 'Acompanhamos os detalhes que ajudam uma expedição a decorrer com clareza: carga, percurso, prazos e comunicação durante a coordenação.', 'Cada pedido é diferente. Ouvimos as necessidades, analisamos opções e acompanhamos a expedição desde a recolha até à entrega.'], cards: [{ title: 'Compreender o pedido', text: 'Começamos pela carga, origem, destino, prazo e requisitos de manuseamento.' }, { title: 'Coordenar o plano', text: 'Analisamos opções rodoviárias adequadas e confirmamos os detalhes do transporte solicitado.' }, { title: 'Manter o contacto', text: 'Mantemos um ponto de contacto claro enquanto a expedição é coordenada.' }] },
      services: { hero: ['Serviços rodoviários', 'A solução certa', 'para cada expedição.', 'Opções flexíveis de transporte rodoviário ajustadas à carga, ao percurso e ao prazo.'], heading: ['Soluções rodoviárias', 'Transporte pensado', 'para a sua carga.'], paragraphs: ['Escolha um serviço para iniciar a conversa. A disponibilidade e os detalhes finais são confirmados para cada expedição.'], cards: [{ icon: 'truck', title: 'Carga completa (FTL)', text: 'Capacidade dedicada para cargas completas, planeada conforme o percurso, a mercadoria e o prazo solicitado.' }, { icon: 'boxes', title: 'Carga parcial (LTL)', text: 'Opções de grupagem para expedições que não precisam de um veículo completo.' }, { icon: 'clock', title: 'Transporte expresso', text: 'Transporte urgente coordenado com comunicação clara e atenção aos prazos acordados.' }, { icon: 'route', title: 'Transporte dedicado', text: 'Um plano de transporte ajustado às necessidades específicas da sua expedição.' }, { icon: 'globe', title: 'Transporte rodoviário europeu', text: 'Coordenação de transporte internacional entre Portugal e destinos europeus selecionados.' }, { icon: 'shield', title: 'Coordenação logística', text: 'Um contacto direto para coordenar a expedição desde a recolha até à entrega.' }] },
      fleet: { hero: ['Frota e rede', 'Capacidade que faz', 'o negócio avançar.', 'Transporte coordenado de acordo com as necessidades de cada expedição.'], heading: ['Frota e rede de transporte', 'Capacidade flexível.', 'Um contacto claro.'], paragraphs: ['A Trevola coordena capacidade de transporte rodoviário de acordo com cada expedição.', 'O tipo de veículo, percurso, requisitos de carga e prazos são analisados em cada pedido. A solução disponível é confirmada antes da reserva.', 'A Trevola Logistics é apresentada como coordenadora de transporte; não declara ser proprietária dos veículos ilustrados.'], cards: [{ title: 'Perfil da expedição', text: 'Analisamos dimensões, peso, tipo de mercadoria, local de recolha e entrega.' }, { title: 'Opção de transporte', text: 'As opções de capacidade e percurso são avaliadas segundo os requisitos da carga.' }, { title: 'Detalhes confirmados', text: 'Os prazos e procedimentos são confirmados antes de o transporte avançar.' }] },
      industries: { hero: ['Setores que apoiamos', 'Transporte ajustado', 'ao seu setor.', 'Uma abordagem cuidada à carga, ao percurso e aos prazos de vários setores.'], heading: ['Setores que apoiamos', 'Transporte rodoviário para', 'diferentes necessidades.'], paragraphs: ['Cada setor tem requisitos próprios. Começamos pela carga, percurso e prazo para analisar uma solução rodoviária adequada.'], cards: [{ icon: 'car', title: 'Automóvel', text: 'Componentes e mercadorias para cadeias de fornecimento automóvel.' }, { icon: 'wheat', title: 'Agricultura', text: 'Planeamento de transporte para produtos e materiais agrícolas.' }, { icon: 'industry', title: 'Equipamento industrial', text: 'Coordenação para máquinas, peças e equipamento industrial.' }, { icon: 'cart', title: 'Retalho', text: 'Transporte de mercadorias para distribuição, reposição e gestão de stock.' }, { icon: 'food', title: 'Alimentação e bebidas', text: 'Coordenação de cargas alimentares conforme os requisitos da expedição.' }, { icon: 'package', title: 'Comércio eletrónico', text: 'Opções de transporte para mercadorias e fluxos de comércio online.' }], note: 'Estas categorias são exemplos de necessidades gerais. Requisitos especiais, mercadorias reguladas e disponibilidade de equipamento devem ser confirmados antes da reserva.' },
      contact: { hero: ['Contactos', 'Vamos iniciar', 'uma conversa.', 'Fale com a Trevola Logistics sobre as suas necessidades de transporte.'], heading: ['Contacte a Trevola Logistics', 'Vamos falar sobre', 'a sua próxima carga.'], paragraphs: ['A nossa equipa está disponível para conversar sobre transporte rodoviário entre Portugal e destinos europeus.', 'Partilhe a origem, o destino, os detalhes da carga e o prazo pretendido. Ajudamos a esclarecer os próximos passos para preparar o pedido.'] },
    },
    quote: { intro: 'Partilhe os detalhes da carga e do percurso. A nossa equipa terá a informação necessária para analisar uma solução adequada.', fieldsTitle: 'O que precisa de transportar?', formTitle: 'Detalhes da expedição', requiredNote: 'Os campos assinalados com * são obrigatórios.', labels: { company: 'Nome da empresa', contact: 'Pessoa de contacto', email: 'Email', phone: 'Número de telefone', pickupCountry: 'País de recolha', pickupCity: 'Cidade de recolha', deliveryCountry: 'País de entrega', deliveryCity: 'Cidade de entrega', transport: 'Tipo de transporte', pallets: 'Número de paletes', cargo: 'Descrição da carga', weight: 'Peso (kg)', volume: 'Volume (m³)', loadingDate: 'Data preferencial de carga', additional: 'Informações adicionais' }, select: 'Selecione o tipo de transporte', errors: { required: 'Preencha este campo.', email: 'Introduza um endereço de email válido.', minimum: 'Introduza um número positivo válido.', date: 'Escolha hoje ou uma data futura.', wholeNumber: 'Introduza um número inteiro.' }, loading: 'A enviar o pedido…', success: 'Obrigado. O seu pedido de orçamento foi enviado à Trevola Logistics.', notConfigured: 'O envio online ainda não está configurado. Nada foi enviado. Contacte info@trevolalogistics.com.', genericError: 'Não foi possível enviar o pedido agora. Tente novamente ou contacte info@trevolalogistics.com.' },
    legal: {
      'privacy-policy': { title: 'Política de Privacidade', sections: [{ title: 'Responsável pelo tratamento', text: 'Este website é operado pela Trevola Logistics, Lda. (NIF 516173812). Para questões de privacidade, contacte info@trevolalogistics.com.' }, { title: 'Informação e finalidades', text: 'Ao enviar um pedido de orçamento, os dados do formulário (empresa, contacto, email, telefone, percurso, carga, peso/volume e data pretendida) são usados para responder ao pedido e preparar uma proposta. O alojamento pode também tratar registos técnicos de segurança.' }, { title: 'Fundamento e destinatários', text: 'Os pedidos de orçamento são tratados para diligências pré-contratuais solicitadas. As mensagens são enviadas para info@trevolalogistics.com através da Resend e da caixa de email empresarial fornecida pela Zoho. A Vercel assegura o alojamento e as funções backend; a Cloudflare assegura o DNS. Faltam confirmar os locais de tratamento, subcontratantes e salvaguardas aplicáveis a eventuais transferências internacionais.' }, { title: 'Conservação e direitos', text: 'Os dados pessoais de pedidos de orçamento sem contrato são conservados durante um mês após o encerramento do pedido. Os dados pessoais de clientes usados na coordenação da expedição e os dados de candidaturas são conservados durante um mês após a conclusão do serviço ou o encerramento da candidatura. Documentos contabilísticos e fiscais sujeitos a conservação obrigatória são guardados pelo prazo legal aplicável. Consoante as regras aplicáveis, poderá solicitar acesso, retificação, apagamento, limitação ou opor-se ao tratamento, e apresentar reclamação à CNPD. Contacte info@trevolalogistics.com para exercer os seus direitos.' }, { title: 'Revisões', text: 'Este modelo deve ser revisto de acordo com a entidade legal, alojamento, fornecedor de email, prazo de conservação e práticas reais. Atualize a data após essa revisão.' }], note: 'Modelo a completar pelo operador do website · Revisto em 9 de outubro de 2026' },
      cookies: { title: 'Política de Cookies', sections: [{ title: 'Armazenamento utilizado atualmente', text: 'O website atual não carrega ferramentas de publicidade ou analítica. Guarda a preferência de idioma no armazenamento local do navegador para memorizar a escolha. Esta preferência funcional não é usada para publicidade nem definição de perfis.' }, { title: 'Tecnologias essenciais', text: 'A plataforma de alojamento poderá usar mecanismos técnicos necessários para disponibilizar e proteger o website. O operador deve confirmar as práticas do fornecedor antes da publicação.' }, { title: 'As suas opções', text: 'Pode remover a preferência de idioma nas definições de dados do website do seu navegador. Se forem acrescentadas ferramentas opcionais de analítica ou marketing, este aviso e a experiência de consentimento devem ser revistos antes da ativação.' }, { title: 'Contactos', text: 'Para questões sobre este aviso ou as tecnologias de armazenamento, contacte info@trevolalogistics.com.' }], note: 'Este aviso descreve o código atual e deve ser confirmado face à configuração final do alojamento.' },
      terms: { title: 'Termos e Condições', sections: [{ title: 'Informação do website', text: 'Este website apresenta informação geral sobre a Trevola Logistics e a coordenação de transporte rodoviário. O conteúdo não constitui uma proposta vinculativa nem confirma a disponibilidade de percurso, veículo ou data.' }, { title: 'Orçamentos e reservas', text: 'Um pedido de orçamento é apenas uma consulta. O âmbito, preço, capacidade, prazo, requisitos de manuseamento e condições contratuais devem ser confirmados por escrito antes de qualquer reserva.' }, { title: 'Precisão e disponibilidade', text: 'A informação, os mapas e as imagens ilustrativas destinam-se a orientação geral. Os percursos, a disponibilidade e os procedimentos são confirmados para cada expedição.' }, { title: 'Propriedade intelectual e contacto', text: 'Os textos, o layout e os materiais de marca não podem ser copiados ou reutilizados sem autorização dos respetivos titulares. Para questões, contacte info@trevolalogistics.com.' }, { title: 'Identificação e lei aplicável', text: 'O operador do website é a Trevola Logistics, Lda. (NIF 516173812). Falta confirmar a lei/jurisdição aplicável antes de finalizar estes termos.' }], note: 'Modelo de termos · Complete e reveja os dados da empresa e jurisdição antes da publicação.' },
    },
    careers: { emptyTitle: 'Não temos vagas abertas neste momento', emptyText: 'Não existem vagas publicadas atualmente. Se quiser apresentar o seu perfil para oportunidades futuras, contacte a nossa equipa por email.', button: 'Contactar a Trevola Logistics' },
    news: { emptyTitle: 'Ainda não há notícias publicadas', emptyText: 'Neste momento não existem artigos publicados. Volte mais tarde para acompanhar novidades da empresa e do setor logístico.' },
    cta: { eyebrow: 'Pronto para avançar?', title: 'Pronto para transportar a sua carga?', text: 'Os nossos especialistas em logística estão prontos para encontrar a melhor solução de transporte para a sua empresa.', quote: 'Pedir orçamento', contact: 'Contactar' },
    seo: {
      home: ['Trevola Logistics | Transporte Rodoviário Europeu', 'Transporte rodoviário internacional entre Portugal e destinos europeus, coordenado pela Trevola Logistics.'],
      'about-us': ['Sobre Nós | Trevola Logistics', 'Conheça a Trevola Logistics, parceira sediada em Portugal para coordenação de transporte rodoviário europeu.'],
      services: ['Serviços de Transporte | Trevola Logistics', 'Conheça opções de transporte rodoviário FTL, LTL, expresso e dedicado para expedições europeias.'],
      fleet: ['Frota e Rede | Trevola Logistics', 'Capacidade de transporte rodoviário coordenada conforme a carga, o percurso e o prazo.'],
      industries: ['Setores | Trevola Logistics', 'Coordenação rodoviária para os setores automóvel, agrícola, retalho, alimentar e outros.'],
      'request-a-quote': ['Pedir Orçamento | Trevola Logistics', 'Partilhe o percurso e os detalhes da carga para pedir um orçamento de transporte rodoviário.'],
      contact: ['Contactos | Trevola Logistics', 'Contacte a Trevola Logistics em Portugal sobre transporte rodoviário internacional.'],
      'privacy-policy': ['Política de Privacidade | Trevola Logistics', 'Saiba como a Trevola Logistics trata dados do website e pedidos de transporte.'],
      cookies: ['Política de Cookies | Trevola Logistics', 'Informação sobre cookies e armazenamento do navegador usados pelo website Trevola Logistics.'],
      terms: ['Termos e Condições | Trevola Logistics', 'Termos do website e dos pedidos de coordenação de transporte rodoviário.'],
      careers: ['Carreiras | Trevola Logistics', 'Oportunidades profissionais e contactos da Trevola Logistics.'],
      news: ['Notícias | Trevola Logistics', 'Novidades da empresa e do setor logístico da Trevola Logistics.'],
    },
  },
  de: {
    label: 'Deutsch',
    nav: { home: 'Startseite', 'about-us': 'Über uns', services: 'Leistungen', fleet: 'Netzwerk', industries: 'Branchen', contact: 'Kontakt', careers: 'Karriere', news: 'Neuigkeiten', quote: 'Angebot anfragen', privacy: 'Datenschutz', cookies: 'Cookies', terms: 'AGB', search: 'Suche', language: 'Sprache' },
    common: { skip: 'Zum Inhalt springen', menuOpen: 'Menü öffnen', menuClose: 'Menü schließen', home: 'Trevola Logistics Startseite', searchPlaceholder: 'Leistungen, Seiten und Informationen suchen', searchClose: 'Suche schließen', searchEmpty: 'Keine passenden Seiten gefunden.', searchLabel: 'Diese Website durchsuchen', breadcrumb: 'Startseite', footerText: 'Internationaler Straßengüterverkehr, sorgfältig koordiniert.', explore: 'Entdecken', contact: 'Kontakt', rights: 'Alle Rechte vorbehalten.', backTop: 'Nach oben', email: 'E-Mail', phone: 'Telefon', website: 'Website', license: 'Speditionslizenz', licenseNumber: 'Nr. 901091', whatsappLabel: 'Trevola Logistics per WhatsApp kontaktieren', basedPortugal: 'In Portugal ansässig', connectedEurope: 'Mit Europa verbunden', requestQuote: 'Angebot anfragen', discuss: 'Sendung besprechen', mapNote: 'Illustrative Karte · Verfügbarkeit ist für jede Sendung zu bestätigen', portugal: 'Portugal', europe: 'Europa' },
    pages: {
      'about-us': { hero: ['Über Trevola', 'Ein Straßengüterverkehrspartner', 'mit klarer Koordination.', 'Klare Kommunikation und praktische Transportplanung zwischen Portugal und Europa.'], heading: ['Ein erreichbarer Partner', 'Straßentransport,', 'klar koordiniert.'], paragraphs: ['Trevola Logistics koordiniert internationalen Straßentransport zwischen Portugal und europäischen Zielen.', 'Wir achten auf die Details einer reibungslosen Sendung: Fracht, Route, Zeitplan und klare Kommunikation während der Koordination.', 'Jede Anfrage ist anders. Wir hören zu, prüfen passende Optionen und begleiten die Sendung von der Abholung bis zur Zustellung.'], cards: [{ title: 'Anforderungen verstehen', text: 'Wir beginnen mit Fracht, Start, Ziel, Zeitplan und Handhabungsanforderungen.' }, { title: 'Plan koordinieren', text: 'Wir besprechen geeignete Straßenverkehrsoptionen und bestätigen die angefragten Details.' }, { title: 'In Kontakt bleiben', text: 'Während der Koordination bleiben wir Ihr klarer Ansprechpartner.' }] },
      services: { hero: ['Straßentransport', 'Die passende Lösung', 'für jede Sendung.', 'Flexible Transportoptionen, abgestimmt auf Fracht, Route und Zeitplan.'], heading: ['Straßentransportlösungen', 'Transport passend', 'zu Ihrer Fracht.'], paragraphs: ['Wählen Sie einen Service, um Ihre Anfrage zu besprechen. Verfügbarkeit und Ablauf werden für jede Sendung bestätigt.'], cards: [{ icon: 'truck', title: 'Komplettladung (FTL)', text: 'Dedizierte Fahrzeugkapazität für Komplettladungen, passend zu Route, Fracht und Lieferzeit.' }, { icon: 'boxes', title: 'Teilladung (LTL)', text: 'Sammelgutoptionen für Sendungen, die kein ganzes Fahrzeug benötigen.' }, { icon: 'clock', title: 'Express-Transport', text: 'Zeitkritische Transporte mit klarer Kommunikation und Blick auf vereinbarte Termine.' }, { icon: 'route', title: 'Dedizierter Transport', text: 'Ein Transportplan passend zu den besonderen Anforderungen Ihrer Sendung.' }, { icon: 'globe', title: 'Europaweiter Straßentransport', text: 'Koordination internationaler Transporte zwischen Portugal und ausgewählten europäischen Zielen.' }, { icon: 'shield', title: 'Logistikkoordination', text: 'Ein direkter Ansprechpartner für die Koordination von Abholung bis Zustellung.' }] },
      fleet: { hero: ['Flotte und Netzwerk', 'Kapazität, die Ihr', 'Geschäft voranbringt.', 'Transportkoordination passend zu den Anforderungen jeder Sendung.'], heading: ['Flotte und Transportnetzwerk', 'Flexible Kapazität.', 'Ein klarer Kontakt.'], paragraphs: ['Trevola koordiniert Transportkapazitäten passend zur jeweiligen Sendung.', 'Fahrzeugtyp, Route, Ladeanforderungen und Zeitplan werden für jede Anfrage besprochen. Die verfügbare Lösung wird vor der Buchung bestätigt.', 'Trevola Logistics wird als Transportkoordinator dargestellt und beansprucht kein Eigentum an den abgebildeten Fahrzeugen.'], cards: [{ title: 'Sendungsprofil', text: 'Wir prüfen Maße, Gewicht, Frachtart sowie Abhol- und Lieferort.' }, { title: 'Transportoption', text: 'Passende Kapazität und Routen werden anhand der Anforderungen besprochen.' }, { title: 'Bestätigte Details', text: 'Zeitplan und Ablauf werden vor Transportbeginn mit Ihnen bestätigt.' }] },
      industries: { hero: ['Branchen', 'Transport passend', 'zu Ihrer Branche.', 'Ein durchdachter Umgang mit Fracht, Route und Zeitplan für verschiedene Branchen.'], heading: ['Branchen, die wir unterstützen', 'Straßentransport für', 'unterschiedliche Anforderungen.'], paragraphs: ['Jede Branche hat eigene Transportanforderungen. Wir betrachten Fracht, Route und Zeitplan und besprechen eine passende Lösung.'], cards: [{ icon: 'car', title: 'Automobil', text: 'Komponenten und Waren für Lieferketten der Automobilindustrie.' }, { icon: 'wheat', title: 'Landwirtschaft', text: 'Transportplanung für landwirtschaftliche Produkte und Materialien.' }, { icon: 'industry', title: 'Industrieausrüstung', text: 'Koordination von Maschinen, Teilen und industrieller Ausrüstung.' }, { icon: 'cart', title: 'Einzelhandel', text: 'Warentransport für Distribution, Nachschub und Bestandsplanung.' }, { icon: 'food', title: 'Lebensmittel und Getränke', text: 'Koordination von Lebensmittelfracht nach den Anforderungen der Sendung.' }, { icon: 'package', title: 'E-Commerce', text: 'Transportoptionen für Online-Handelswaren und Warenflüsse.' }], note: 'Die Kategorien zeigen allgemeine Frachtanforderungen. Sonderbehandlung, regulierte Waren und Ausrüstung müssen vor der Buchung bestätigt werden.' },
      contact: { hero: ['Kontakt', 'Lassen Sie uns', 'ins Gespräch kommen.', 'Sprechen Sie mit Trevola Logistics über Ihre Transportanforderungen.'], heading: ['Trevola Logistics kontaktieren', 'Sprechen wir über', 'Ihre nächste Sendung.'], paragraphs: ['Unser Team bespricht Straßentransporte zwischen Portugal und europäischen Zielen.', 'Teilen Sie Start, Ziel, Frachtdetails und gewünschten Zeitplan mit. Wir erläutern die nächsten Schritte für Ihre Anfrage.'] },
    },
    quote: { intro: 'Teilen Sie uns Fracht- und Routendetails mit. Unser Team erhält so die nötigen Informationen, um eine passende Lösung zu besprechen.', fieldsTitle: 'Was möchten Sie transportieren?', formTitle: 'Angaben zur Sendung', requiredNote: 'Mit * markierte Felder sind Pflichtfelder.', labels: { company: 'Unternehmen', contact: 'Ansprechpartner', email: 'E-Mail', phone: 'Telefonnummer', pickupCountry: 'Abholland', pickupCity: 'Abholort', deliveryCountry: 'Zielland', deliveryCity: 'Lieferort', transport: 'Transportart', pallets: 'Anzahl Paletten', cargo: 'Frachtbeschreibung', weight: 'Gewicht (kg)', volume: 'Volumen (m³)', loadingDate: 'Gewünschtes Ladedatum', additional: 'Zusätzliche Informationen' }, select: 'Transportart wählen', errors: { required: 'Bitte füllen Sie dieses Feld aus.', email: 'Bitte geben Sie eine gültige E-Mail-Adresse ein.', minimum: 'Bitte geben Sie eine gültige positive Zahl ein.', date: 'Wählen Sie heute oder ein zukünftiges Datum.', wholeNumber: 'Geben Sie eine ganze Zahl ein.' }, loading: 'Anfrage wird gesendet…', success: 'Vielen Dank. Ihre Angebotsanfrage wurde an Trevola Logistics gesendet.', notConfigured: 'Der Online-Versand ist noch nicht eingerichtet. Es wurde nichts gesendet. Bitte schreiben Sie an info@trevolalogistics.com.', genericError: 'Die Anfrage konnte gerade nicht gesendet werden. Bitte versuchen Sie es erneut oder schreiben Sie an info@trevolalogistics.com.' },
    legal: {
      'privacy-policy': { title: 'Datenschutzerklärung', sections: [{ title: 'Verantwortliche Stelle', text: 'Diese Website wird von Trevola Logistics, Lda. (portugiesische Steuernummer, NIF: 516173812) betrieben. Datenschutzkontakt: info@trevolalogistics.com.' }, { title: 'Daten und Zwecke', text: 'Wenn Sie eine Angebotsanfrage senden, werden die Formularangaben (Unternehmen, Kontaktdaten, E-Mail, Telefon, Route, Fracht, Gewicht/Volumen und gewünschter Termin) zur Beantwortung und Erstellung eines möglichen Angebots verwendet. Der Hosting-Anbieter kann außerdem technische Sicherheitsprotokolle verarbeiten.' }, { title: 'Rechtsgrundlage und Empfänger', text: 'Anfragedaten werden für vorvertragliche Schritte auf Wunsch der anfragenden Person verarbeitet. Nachrichten werden über Resend und das von Zoho bereitgestellte Firmenpostfach an info@trevolalogistics.com gesendet. Vercel stellt Hosting und Backend-Funktionen bereit; Cloudflare den DNS-Dienst. Verarbeitungsorte, Unterauftragsverarbeiter und Garantien für mögliche internationale Übermittlungen müssen noch bestätigt werden.' }, { title: 'Speicherung und Rechte', text: 'Personenbezogene Daten aus Angebotsanfragen ohne Vertragsabschluss werden nach Abschluss der Anfrage einen Monat aufbewahrt. Personenbezogene Kundendaten zur Koordination eines Transports sowie Bewerbungsdaten werden nach Abschluss des Auftrags beziehungsweise des Bewerbungsverfahrens einen Monat aufbewahrt. Buchhaltungs- und Steuerunterlagen, für die eine gesetzliche Aufbewahrungspflicht gilt, werden für die gesetzlich vorgeschriebene Dauer aufbewahrt. Je nach geltendem Recht können Sie Auskunft, Berichtigung, Löschung oder Einschränkung verlangen, Widerspruch einlegen und sich bei der portugiesischen Datenschutzbehörde CNPD beschweren. Kontakt: info@trevolalogistics.com.' }, { title: 'Aktualisierung', text: 'Dieser Entwurf muss mit der tatsächlichen Gesellschaft, dem Hosting, E-Mail-Anbieter, Speicherfristen und Verarbeitungspraktiken abgeglichen werden. Das Datum nach der Prüfung aktualisieren.' }], note: 'Entwurf zur Ergänzung durch den Websitebetreiber · Geprüft am 9. Oktober 2026' },
      cookies: { title: 'Cookie-Richtlinie', sections: [{ title: 'Aktuelle Speicherung', text: 'Die Website lädt derzeit keine Werbe- oder Analysetools. Die gewählte Sprache wird im lokalen Browserspeicher gespeichert, damit die Einstellung erhalten bleibt. Diese funktionale Präferenz dient weder Werbung noch Profilbildung.' }, { title: 'Notwendige Technologien', text: 'Der Hosting-Anbieter kann technische Funktionen verwenden, die für Bereitstellung und Sicherheit der Website erforderlich sind. Der Betreiber sollte dessen Speicher- und Protokollierungspraxis vor Veröffentlichung prüfen.' }, { title: 'Ihre Optionen', text: 'Die gespeicherte Sprachpräferenz lässt sich über die Website-Dateneinstellungen des Browsers entfernen. Werden später optionale Analyse- oder Marketingdienste ergänzt, müssen Hinweis und Einwilligungsablauf vor deren Aktivierung geprüft werden.' }, { title: 'Kontakt', text: 'Fragen zu diesem Hinweis oder den Speichertechnologien richten Sie an info@trevolalogistics.com.' }], note: 'Dieser Hinweis beschreibt den aktuellen Website-Code und muss mit dem endgültigen Hosting abgeglichen werden.' },
      terms: { title: 'Allgemeine Geschäftsbedingungen', sections: [{ title: 'Website-Informationen', text: 'Diese Website enthält allgemeine Informationen über Trevola Logistics und die Koordination von Straßentransporten. Inhalte sind kein verbindliches Angebot und bestätigen nicht die Verfügbarkeit einer Route, eines Fahrzeugs oder eines Termins.' }, { title: 'Angebote und Buchungen', text: 'Eine Angebotsanfrage ist zunächst unverbindlich. Umfang, Preis, Kapazität, Zeitplan, Handhabung und Vertragsbedingungen müssen vor einer Buchung schriftlich bestätigt werden.' }, { title: 'Richtigkeit und Verfügbarkeit', text: 'Angaben, Karten und illustrative Bilder dienen der allgemeinen Orientierung. Routen, Verfügbarkeit und Ablauf werden für jede Sendung bestätigt.' }, { title: 'Geistiges Eigentum und Kontakt', text: 'Website-Texte, Layout und Markenmaterialien dürfen ohne Genehmigung der Rechteinhaber nicht kopiert oder wiederverwendet werden. Fragen: info@trevolalogistics.com.' }, { title: 'Betreiber und anwendbares Recht', text: 'Betreiberin dieser Website ist Trevola Logistics, Lda. (portugiesische Steuernummer, NIF: 516173812). Anwendbares Recht und Gerichtsstand müssen vor der endgültigen Fassung dieser Bedingungen noch bestätigt werden.' }], note: 'Entwurf · Unternehmens- und Gerichtsstandangaben vor Veröffentlichung ergänzen.' },
    },
    careers: { emptyTitle: 'Derzeit keine offenen Stellen', emptyText: 'Aktuell sind keine Stellen ausgeschrieben. Wenn Sie sich für zukünftige Möglichkeiten vorstellen möchten, schreiben Sie unserem Team per E-Mail.', button: 'Trevola Logistics kontaktieren' },
    news: { emptyTitle: 'Noch keine Neuigkeiten veröffentlicht', emptyText: 'Zurzeit gibt es keine Artikel. Besuchen Sie uns später wieder für Neuigkeiten aus dem Unternehmen und der Logistikbranche.' },
    cta: { eyebrow: 'Bereit für den nächsten Schritt?', title: 'Bereit, Ihre Fracht zu bewegen?', text: 'Unsere Logistikexperten finden die passende Transportlösung für Ihr Unternehmen.', quote: 'Angebot anfragen', contact: 'Kontakt aufnehmen' },
    seo: {
      home: ['Trevola Logistics | Europäischer Straßentransport', 'Internationaler Straßengüterverkehr zwischen Portugal und europäischen Zielen, koordiniert von Trevola Logistics.'],
      'about-us': ['Über uns | Trevola Logistics', 'Trevola Logistics ist ein portugiesischer Partner für koordinierten Straßentransport in Europa.'],
      services: ['Straßentransport | Trevola Logistics', 'FTL-, LTL-, Express- und dedizierte Transportkoordination für europäische Sendungen.'],
      fleet: ['Flotte und Netzwerk | Trevola Logistics', 'Transportkapazität passend zu Frachtanforderungen, Routen und Zeitplänen.'],
      industries: ['Branchen | Trevola Logistics', 'Straßentransportkoordination für Automobil, Landwirtschaft, Einzelhandel, Lebensmittel und weitere Branchen.'],
      'request-a-quote': ['Angebot anfragen | Trevola Logistics', 'Fracht- und Routendetails für eine Straßentransportanfrage an Trevola Logistics teilen.'],
      contact: ['Kontakt | Trevola Logistics', 'Kontaktieren Sie Trevola Logistics in Portugal zu internationalem Straßentransport.'],
      'privacy-policy': ['Datenschutz | Trevola Logistics', 'Informationen zur Verarbeitung von Website- und Transportanfragedaten durch Trevola Logistics.'],
      cookies: ['Cookies | Trevola Logistics', 'Informationen zu Cookies und Browser-Speicherung auf der Trevola Logistics Website.'],
      terms: ['AGB | Trevola Logistics', 'Website- und Anfragebedingungen für die Straßentransportkoordination von Trevola Logistics.'],
      careers: ['Karriere | Trevola Logistics', 'Karriere und Kontaktinformationen von Trevola Logistics.'],
      news: ['Neuigkeiten | Trevola Logistics', 'Unternehmens- und Logistikneuigkeiten von Trevola Logistics.'],
    },
  },
  fr: {
    label: 'Français',
    nav: { home: 'Accueil', 'about-us': 'À propos', services: 'Services', fleet: 'Réseau', industries: 'Secteurs', contact: 'Contact', careers: 'Carrières', news: 'Actualités', quote: 'Demander un devis', privacy: 'Confidentialité', cookies: 'Cookies', terms: 'Conditions', search: 'Rechercher', language: 'Langue' },
    common: { skip: 'Aller au contenu', menuOpen: 'Ouvrir le menu', menuClose: 'Fermer le menu', home: 'Accueil Trevola Logistics', searchPlaceholder: 'Rechercher des services et des informations', searchClose: 'Fermer la recherche', searchEmpty: 'Aucune page correspondante.', searchLabel: 'Rechercher sur ce site', breadcrumb: 'Accueil', footerText: 'Transport routier international, coordonné avec soin.', explore: 'Explorer', contact: 'Contact', rights: 'Tous droits réservés.', backTop: 'Retour en haut', email: 'E-mail', phone: 'Téléphone', website: 'Site web', license: 'Licence de commissionnaire de transport', licenseNumber: 'N° 901091', whatsappLabel: 'Contacter Trevola Logistics sur WhatsApp', basedPortugal: 'Basés au Portugal', connectedEurope: 'Connectés à l’Europe', requestQuote: 'Demander un devis', discuss: 'Parler de votre expédition', mapNote: 'Carte illustrative · disponibilité à confirmer pour chaque expédition', portugal: 'Portugal', europe: 'Europe' },
    pages: {
      'about-us': { hero: ['À propos de Trevola', 'Un partenaire routier', 'à la coordination claire.', 'Une communication claire et une planification pratique entre le Portugal et l’Europe.'], heading: ['Un partenaire accessible', 'Le transport routier,', 'en toute clarté.'], paragraphs: ['Trevola Logistics coordonne le transport routier international entre le Portugal et des destinations européennes.', 'Nous suivons les détails utiles à une expédition fluide : marchandise, itinéraire, délais et communication.', 'Chaque demande est différente. Nous étudions des options adaptées et restons disponibles du départ à la livraison.'], cards: [{ title: 'Comprendre le besoin', text: 'Nous commençons par la marchandise, le départ, la destination, le délai et les exigences de manutention.' }, { title: 'Coordonner le plan', text: 'Nous étudions des options routières et confirmons les détails du transport demandé.' }, { title: 'Rester en contact', text: 'Nous restons votre interlocuteur pendant la coordination de l’expédition.' }] },
      services: { hero: ['Transport routier', 'La bonne solution', 'pour chaque envoi.', 'Des options flexibles adaptées à la marchandise, au trajet et aux délais.'], heading: ['Solutions routières', 'Un transport adapté', 'à votre marchandise.'], paragraphs: ['Choisissez un service pour commencer. Disponibilité et organisation sont confirmées pour chaque expédition.'], cards: [{ icon: 'truck', title: 'Chargement complet (FTL)', text: 'Capacité dédiée aux chargements complets, planifiée selon la route, la marchandise et le délai souhaité.' }, { icon: 'boxes', title: 'Chargement partiel (LTL)', text: 'Des solutions de groupage pour les expéditions ne nécessitant pas un véhicule complet.' }, { icon: 'clock', title: 'Transport express', text: 'Transport urgent coordonné avec une communication claire et le suivi des délais convenus.' }, { icon: 'route', title: 'Transport dédié', text: 'Un plan adapté aux besoins précis de votre expédition.' }, { icon: 'globe', title: 'Transport routier européen', text: 'Coordination du transport international entre le Portugal et des destinations européennes.' }, { icon: 'shield', title: 'Coordination logistique', text: 'Un interlocuteur direct de l’enlèvement à la livraison.' }] },
      fleet: { hero: ['Flotte et réseau', 'Une capacité qui fait', 'avancer votre activité.', 'Un transport coordonné selon les besoins de chaque expédition.'], heading: ['Flotte et réseau de transport', 'Une capacité flexible.', 'Un contact unique.'], paragraphs: ['Trevola coordonne des capacités de transport adaptées à chaque expédition.', 'Le véhicule, l’itinéraire, le chargement et les délais sont étudiés pour chaque demande. La solution disponible est confirmée avant réservation.', 'Trevola Logistics est présentée comme coordinatrice de transport et ne revendique pas la propriété des véhicules illustrés.'], cards: [{ title: 'Profil de l’envoi', text: 'Nous examinons dimensions, poids, nature de la marchandise et lieux de collecte et livraison.' }, { title: 'Option de transport', text: 'Les capacités et itinéraires adaptés sont étudiés selon les besoins.' }, { title: 'Détails confirmés', text: 'Les délais et modalités sont confirmés avant le transport.' }] },
      industries: { hero: ['Secteurs accompagnés', 'Un transport adapté', 'à votre secteur.', 'Une approche réfléchie de la marchandise, du trajet et des délais.'], heading: ['Secteurs accompagnés', 'Du transport routier pour', 'différents besoins.'], paragraphs: ['Chaque secteur a ses exigences. Nous étudions la marchandise, l’itinéraire et les délais pour proposer une solution adaptée.'], cards: [{ icon: 'car', title: 'Automobile', text: 'Composants et marchandises pour les chaînes d’approvisionnement automobiles.' }, { icon: 'wheat', title: 'Agriculture', text: 'Planification du transport de produits et matériaux agricoles.' }, { icon: 'industry', title: 'Équipements industriels', text: 'Coordination de machines, pièces et équipements industriels.' }, { icon: 'cart', title: 'Commerce de détail', text: 'Transport pour la distribution, le réapprovisionnement et les stocks.' }, { icon: 'food', title: 'Alimentation et boissons', text: 'Coordination des marchandises alimentaires selon les besoins de l’envoi.' }, { icon: 'package', title: 'Commerce en ligne', text: 'Options de transport pour les marchandises du commerce en ligne.' }], note: 'Ces catégories illustrent des besoins généraux. Les exigences spéciales, marchandises réglementées et équipements doivent être confirmés avant réservation.' },
      contact: { hero: ['Contact', 'Commençons', 'la conversation.', 'Parlez à Trevola Logistics de vos besoins de transport routier.'], heading: ['Contacter Trevola Logistics', 'Parlons de', 'votre prochaine expédition.'], paragraphs: ['Notre équipe échange sur le transport routier entre le Portugal et les destinations européennes.', 'Indiquez l’origine, la destination, la marchandise et le délai souhaité. Nous vous expliquons les prochaines étapes.'] },
    },
    quote: { intro: 'Partagez les détails de la marchandise et du trajet. Notre équipe pourra étudier une solution adaptée.', fieldsTitle: 'Que souhaitez-vous transporter ?', formTitle: 'Détails de l’expédition', requiredNote: 'Les champs suivis de * sont obligatoires.', labels: { company: 'Entreprise', contact: 'Personne à contacter', email: 'E-mail', phone: 'Téléphone', pickupCountry: 'Pays de collecte', pickupCity: 'Ville de collecte', deliveryCountry: 'Pays de livraison', deliveryCity: 'Ville de livraison', transport: 'Type de transport', pallets: 'Nombre de palettes', cargo: 'Description de la marchandise', weight: 'Poids (kg)', volume: 'Volume (m³)', loadingDate: 'Date de chargement souhaitée', additional: 'Informations complémentaires' }, select: 'Choisir le type de transport', errors: { required: 'Veuillez remplir ce champ.', email: 'Saisissez une adresse e-mail valide.', minimum: 'Saisissez un nombre positif valide.', date: 'Choisissez aujourd’hui ou une date ultérieure.', wholeNumber: 'Saisissez un nombre entier.' }, loading: 'Envoi de la demande…', success: 'Merci. Votre demande de devis a été envoyée à Trevola Logistics.', notConfigured: 'L’envoi en ligne n’est pas encore configuré. Rien n’a été envoyé. Écrivez à info@trevolalogistics.com.', genericError: 'La demande n’a pas pu être envoyée. Réessayez ou écrivez à info@trevolalogistics.com.' },
    legal: {
      'privacy-policy': { title: 'Politique de confidentialité', sections: [{ title: 'Responsable du traitement', text: 'Ce site est exploité par Trevola Logistics, Lda. (numéro fiscal portugais, NIF : 516173812). Contact confidentialité : info@trevolalogistics.com.' }, { title: 'Données et finalités', text: 'Lorsque vous envoyez une demande de devis, les données du formulaire (entreprise, coordonnées, e-mail, téléphone, trajet, marchandise, poids/volume et date souhaitée) servent à répondre à la demande et préparer une proposition. L’hébergeur peut également traiter des journaux techniques de sécurité.' }, { title: 'Base et destinataires', text: 'Les demandes de devis sont traitées pour les démarches précontractuelles sollicitées. Les messages sont envoyés à info@trevolalogistics.com via Resend et la messagerie professionnelle fournie par Zoho. Vercel assure l’hébergement et les fonctions backend ; Cloudflare assure le DNS. Les lieux de traitement, sous-traitants ultérieurs et garanties applicables aux éventuels transferts internationaux restent à confirmer.' }, { title: 'Conservation et droits', text: 'Les données personnelles des demandes de devis sans contrat sont conservées pendant un mois après la clôture de la demande. Les données personnelles des clients utilisées pour coordonner une expédition et les données des candidatures sont conservées pendant un mois après la fin du service ou la clôture de la candidature. Les documents comptables et fiscaux soumis à une obligation de conservation sont gardés pendant la durée prévue par la loi. Selon les règles applicables, vous pouvez demander l’accès, la rectification, l’effacement ou la limitation, vous opposer au traitement et déposer une plainte auprès de la CNPD. Contact : info@trevolalogistics.com.' }, { title: 'Mise à jour', text: 'Ce modèle doit être adapté à l’entité juridique, à l’hébergement, au prestataire e-mail, à la durée de conservation et aux pratiques réelles. Actualisez la date après vérification.' }], note: 'Modèle à compléter par l’exploitant · Révisé le 9 octobre 2026' },
      cookies: { title: 'Politique relative aux cookies', sections: [{ title: 'Stockage utilisé actuellement', text: 'Le site actuel ne charge aucun outil publicitaire ou analytique. Il mémorise la langue choisie dans le stockage local du navigateur. Cette préférence fonctionnelle n’est utilisée ni pour la publicité ni pour le profilage.' }, { title: 'Technologies nécessaires', text: 'L’hébergeur peut utiliser des mécanismes techniques nécessaires à la diffusion et à la sécurité du site. L’exploitant doit vérifier ses pratiques avant publication.' }, { title: 'Vos choix', text: 'Vous pouvez supprimer la préférence linguistique dans les paramètres de données du site de votre navigateur. Si des outils facultatifs d’analyse ou de marketing sont ajoutés, cet avis et le mécanisme de consentement doivent être révisés avant leur activation.' }, { title: 'Contact', text: 'Pour toute question sur cet avis ou le stockage, écrivez à info@trevolalogistics.com.' }], note: 'Cet avis décrit le code actuel et doit être vérifié avec l’hébergement final.' },
      terms: { title: 'Conditions générales', sections: [{ title: 'Informations du site', text: 'Ce site présente des informations générales sur Trevola Logistics et la coordination du transport routier. Son contenu n’est pas une offre ferme et ne confirme pas la disponibilité d’un itinéraire, d’un véhicule ou d’une date.' }, { title: 'Devis et réservations', text: 'Une demande de devis est une simple demande d’information. Le périmètre, le prix, la capacité, les délais, la manutention et les conditions contractuelles doivent être confirmés par écrit avant réservation.' }, { title: 'Exactitude et disponibilité', text: 'Les informations, cartes et images illustratives sont fournies à titre indicatif. Les itinéraires et modalités sont confirmés pour chaque expédition.' }, { title: 'Propriété intellectuelle et contact', text: 'Les textes, la mise en page et les éléments de marque ne peuvent être copiés ou réutilisés sans l’autorisation des ayants droit. Contact : info@trevolalogistics.com.' }, { title: 'Exploitant et droit applicable', text: 'L’exploitant du site est Trevola Logistics, Lda. (numéro fiscal portugais, NIF : 516173812). Le droit et la juridiction applicables restent à confirmer avant finalisation de ces conditions.' }], note: 'Modèle · Compléter les coordonnées de l’entreprise et la juridiction avant publication.' },
    },
    careers: { emptyTitle: 'Aucun poste à pourvoir actuellement', emptyText: 'Aucune offre n’est publiée pour le moment. Pour vous présenter en vue de futures opportunités, contactez notre équipe par e-mail.', button: 'Contacter Trevola Logistics' },
    news: { emptyTitle: 'Aucune actualité publiée', emptyText: 'Aucun article n’est disponible pour le moment. Revenez plus tard pour les nouvelles de l’entreprise et de la logistique.' },
    cta: { eyebrow: 'Prêt à avancer ?', title: 'Prêt à transporter votre marchandise ?', text: 'Nos experts logistiques trouveront la meilleure solution de transport pour votre entreprise.', quote: 'Demander un devis', contact: 'Nous contacter' },
    seo: {
      home: ['Trevola Logistics | Transport routier européen', 'Transport routier international entre le Portugal et les destinations européennes, coordonné par Trevola Logistics.'],
      'about-us': ['À propos | Trevola Logistics', 'Découvrez Trevola Logistics, partenaire portugais de coordination du transport routier en Europe.'],
      services: ['Services routiers | Trevola Logistics', 'Solutions FTL, LTL, express et transport dédié pour vos expéditions européennes.'],
      fleet: ['Flotte et réseau | Trevola Logistics', 'Capacité de transport coordonnée selon la marchandise, l’itinéraire et les délais.'],
      industries: ['Secteurs | Trevola Logistics', 'Coordination routière pour l’automobile, l’agriculture, le commerce, l’alimentation et d’autres secteurs.'],
      'request-a-quote': ['Demander un devis | Trevola Logistics', 'Partagez le trajet et les caractéristiques de votre marchandise pour demander un devis.'],
      contact: ['Contact | Trevola Logistics', 'Contactez Trevola Logistics au Portugal pour le transport routier international.'],
      'privacy-policy': ['Confidentialité | Trevola Logistics', 'Comment Trevola Logistics traite les informations du site et les demandes de transport.'],
      cookies: ['Cookies | Trevola Logistics', 'Informations sur les cookies et le stockage du navigateur utilisés par le site.'],
      terms: ['Conditions générales | Trevola Logistics', 'Conditions du site et des demandes de coordination du transport routier.'],
      careers: ['Carrières | Trevola Logistics', 'Opportunités et coordonnées de Trevola Logistics.'],
      news: ['Actualités | Trevola Logistics', 'Actualités de l’entreprise et du secteur logistique par Trevola Logistics.'],
    },
  },
  ru: {
    label: 'Русский',
    nav: { home: 'Главная', 'about-us': 'О компании', services: 'Услуги', fleet: 'Сеть перевозок', industries: 'Отрасли', contact: 'Контакты', careers: 'Карьера', news: 'Новости', quote: 'Запросить расчёт', privacy: 'Конфиденциальность', cookies: 'Файлы cookie', terms: 'Условия', search: 'Поиск', language: 'Язык' },
    common: { skip: 'Перейти к содержимому', menuOpen: 'Открыть меню', menuClose: 'Закрыть меню', home: 'Главная страница Trevola Logistics', searchPlaceholder: 'Поиск услуг, страниц и информации', searchClose: 'Закрыть поиск', searchEmpty: 'Совпадений не найдено.', searchLabel: 'Поиск по сайту', breadcrumb: 'Главная', footerText: 'Международные автомобильные перевозки с чёткой координацией.', explore: 'Разделы сайта', contact: 'Контакты', rights: 'Все права защищены.', backTop: 'Наверх', email: 'Электронная почта', phone: 'Телефон', website: 'Сайт', license: 'Лицензия экспедитора', licenseNumber: '№ 901091', whatsappLabel: 'Связаться с Trevola Logistics в WhatsApp', basedPortugal: 'Компания находится в Португалии', connectedEurope: 'Соединяем Португалию с Европой', requestQuote: 'Запросить расчёт', discuss: 'Обсудить перевозку', mapNote: 'Иллюстративная карта · доступность маршрута подтверждается для каждой перевозки', portugal: 'Португалия', europe: 'Европа' },
    pages: {
      'about-us': { hero: ['О Trevola', 'Партнёр по автоперевозкам', 'с продуманной координацией.', 'Понятная коммуникация и практичное планирование перевозок между Португалией и Европой.'], heading: ['Всегда на связи', 'Автоперевозки,', 'понятно и надёжно.'], paragraphs: ['Trevola Logistics координирует международные автомобильные перевозки из Португалии в страны Европы.', 'Мы уделяем внимание деталям, от которых зависит ход перевозки: уточняем груз, согласуем маршрут и сроки, поддерживаем связь на всех этапах координации.', 'Каждый запрос индивидуален. Мы выслушиваем ваши задачи, подбираем подходящие варианты и сопровождаем перевозку от отправки до доставки.'], cards: [{ title: 'Уточняем задачу', text: 'Сначала выясняем характеристики груза, место отправления и назначения, сроки и требования к обработке.' }, { title: 'Согласуем план', text: 'Обсуждаем подходящие варианты автоперевозки и подтверждаем детали маршрута.' }, { title: 'Остаёмся на связи', text: 'Во время координации перевозки вы знаете, к кому обратиться за информацией.' }] },
      services: { hero: ['Автомобильные перевозки', 'Подходящее решение', 'для каждой перевозки.', 'Гибкие варианты автоперевозок с учётом груза, маршрута и сроков.'], heading: ['Решения для автоперевозок', 'Подходящий транспорт', 'для вашего груза.'], paragraphs: ['Выберите услугу, чтобы обсудить перевозку. Доступность и окончательные условия подтверждаются отдельно для каждого заказа.'], cards: [{ icon: 'truck', title: 'Полная загрузка (FTL)', text: 'Отдельный транспорт для полной загрузки с маршрутом и сроками, согласованными с учётом вашего груза.' }, { icon: 'boxes', title: 'Сборный груз (LTL)', text: 'Гибкая отправка сборного груза, когда для перевозки не нужен отдельный автомобиль.' }, { icon: 'clock', title: 'Срочная перевозка', text: 'Координация срочных перевозок с оперативной связью и соблюдением согласованных сроков.' }, { icon: 'route', title: 'Выделенный транспорт', text: 'План перевозки, составленный с учётом конкретных требований вашего заказа.' }, { icon: 'globe', title: 'Перевозки по Европе', text: 'Координация международных автоперевозок из Португалии в выбранные страны Европы.' }, { icon: 'shield', title: 'Логистическая координация', text: 'Персональный контакт для сопровождения перевозки от отправки до доставки.' }] },
      fleet: { hero: ['Транспортная сеть', 'Возможности, которые', 'помогают бизнесу расти.', 'Транспорт подбирается с учётом потребностей каждой перевозки.'], heading: ['Транспортная сеть', 'Гибкие возможности.', 'Один понятный контакт.'], paragraphs: ['Trevola координирует транспортные возможности под конкретную перевозку, а не предлагает одно решение для всех.', 'Тип автомобиля, маршрут, условия погрузки и сроки обсуждаются по каждому запросу. Вариант перевозки подтверждается до бронирования.', 'Trevola Logistics выступает координатором перевозок и не заявляет, что владеет изображёнными автомобилями.'], cards: [{ title: 'Параметры перевозки', text: 'Уточняем размеры и вес, вид груза, место отправления и требования к доставке.' }, { title: 'Вариант перевозки', text: 'Подбираем вместимость автомобиля и маршрут с учётом требований к грузу.' }, { title: 'Подтверждение деталей', text: 'До начала перевозки согласуем с вами сроки и организационные условия.' }] },
      industries: { hero: ['Отрасли', 'Перевозки с учётом', 'особенностей вашей сферы.', 'Внимательно подходим к грузу, маршруту и срокам в разных отраслях.'], heading: ['Отрасли', 'Автоперевозки', 'для разных задач.'], paragraphs: ['У каждой отрасли свои требования к перевозке. Мы уточняем груз, маршрут и сроки, а затем обсуждаем подходящий вариант автоперевозки.'], cards: [{ icon: 'car', title: 'Автомобильная отрасль', text: 'Комплектующие и товары для цепочек поставок автопрома.' }, { icon: 'wheat', title: 'Сельское хозяйство', text: 'Планирование перевозок сельскохозяйственной продукции и материалов.' }, { icon: 'industry', title: 'Промышленное оборудование', text: 'Координация перевозок оборудования, деталей и промышленной техники.' }, { icon: 'cart', title: 'Розничная торговля', text: 'Перевозка товаров для распределения, пополнения и управления запасами.' }, { icon: 'food', title: 'Продукты и напитки', text: 'Координация продовольственных грузов с учётом требований к перевозке.' }, { icon: 'package', title: 'Электронная торговля', text: 'Варианты перевозок товаров интернет-магазинов и потоков заказов.' }], note: 'Это примеры общих задач по перевозке. Особые условия обработки, регулируемые категории грузов и доступность оборудования необходимо подтвердить до бронирования.' },
      contact: { hero: ['Контакты', 'Давайте обсудим', 'вашу перевозку.', 'Свяжитесь с Trevola Logistics по вопросам автомобильных перевозок.'], heading: ['Связаться с Trevola Logistics', 'Обсудим', 'вашу следующую перевозку.'], paragraphs: ['Наша команда готова обсудить автоперевозку из Португалии в страны Европы.', 'Сообщите пункт отправления и назначения, параметры груза и желаемые сроки. Мы объясним дальнейшие шаги и расскажем, какие сведения нужны для запроса.'] },
    },
    quote: { intro: 'Укажите сведения о грузе и маршруте. Это поможет нашей логистической команде подобрать подходящий вариант.', fieldsTitle: 'Что нужно перевезти?', formTitle: 'Сведения о перевозке', requiredNote: 'Поля, отмеченные *, обязательны.', labels: { company: 'Название компании', contact: 'Контактное лицо', email: 'Электронная почта', phone: 'Телефон', pickupCountry: 'Страна отправления', pickupCity: 'Город отправления', deliveryCountry: 'Страна доставки', deliveryCity: 'Город доставки', transport: 'Тип перевозки', pallets: 'Количество палет', cargo: 'Описание груза', weight: 'Вес (кг)', volume: 'Объём (м³)', loadingDate: 'Желаемая дата погрузки', additional: 'Дополнительная информация' }, select: 'Выберите тип перевозки', errors: { required: 'Заполните это поле.', email: 'Введите корректный адрес электронной почты.', minimum: 'Введите корректное положительное число.', date: 'Выберите сегодняшнюю или более позднюю дату.', wholeNumber: 'Введите целое число.' }, loading: 'Отправка запроса…', success: 'Спасибо. Запрос расчёта отправлен в Trevola Logistics.', notConfigured: 'Онлайн-отправка пока не настроена. Ничего не отправлено. Напишите на info@trevolalogistics.com.', genericError: 'Не удалось отправить запрос. Попробуйте ещё раз или напишите на info@trevolalogistics.com.' },
    legal: {
      'privacy-policy': { title: 'Политика конфиденциальности', sections: [{ title: 'Контролёр персональных данных', text: 'Сайт принадлежит Trevola Logistics, Lda. (португальский налоговый номер (NIF): 516173812). По вопросам конфиденциальности пишите на info@trevolalogistics.com.' }, { title: 'Какие данные и зачем мы используем', text: 'При отправке запроса на расчёт данные формы (компания и контактное лицо, электронная почта, телефон, маршрут, сведения о грузе, вес/объём и желаемая дата) используются для ответа и подготовки возможного предложения. Хостинг-провайдер также может обрабатывать технические журналы безопасности.' }, { title: 'Основание и получатели', text: 'Запросы обрабатываются для действий по просьбе пользователя до заключения договора. Сообщения отправляются на info@trevolalogistics.com через Resend и корпоративную почту Zoho. Vercel предоставляет хостинг и серверные функции; Cloudflare обслуживает DNS. Перед публикацией необходимо уточнить, где обрабатываются данные, какие субподрядчики привлекаются и какие гарантии применяются при возможной международной передаче данных.' }, { title: 'Срок хранения и ваши права', text: 'Персональные данные по запросам, не перешедшим в договор, хранятся один месяц после закрытия запроса. Персональные данные клиентов, используемые для координации перевозки, и данные соискателей хранятся один месяц после завершения услуги или рассмотрения заявки. Бухгалтерские и налоговые документы, для которых законом установлен обязательный срок хранения, хранятся в течение этого срока. Согласно законодательству о защите персональных данных вы можете запросить доступ, исправление, удаление или ограничение обработки, возразить против обработки, а также подать жалобу в португальский орган по защите данных CNPD. Запросы направляйте на info@trevolalogistics.com.' }, { title: 'Обновления', text: 'Перед публикацией оператору необходимо сверить этот проект с юридическими данными компании, настройками хостинга и почты, фактическими сроками хранения и реальными процессами. Дату ниже следует обновить после проверки.' }], note: 'Проект для проверки оператором сайта · Последняя проверка: 9 октября 2026 г.' },
      cookies: { title: 'Политика использования файлов cookie', sections: [{ title: 'Хранение данных на сайте', text: 'Сайт не загружает рекламные или аналитические инструменты. Выбранный язык сохраняется в локальном хранилище браузера, чтобы запомнить ваши настройки. Эти данные нужны только для работы сайта и не используются для рекламы или составления профиля.' }, { title: 'Необходимые технологии', text: 'Хостинг-платформа может использовать технические механизмы для работы и защиты сайта. Оператору следует проверить практики хранения данных и журналов у провайдера до публикации.' }, { title: 'Ваш выбор', text: 'Вы можете удалить сохранённые настройки языка в разделе данных сайта в браузере. Если позднее будут добавлены аналитические или маркетинговые инструменты, этот текст и механизм согласия нужно пересмотреть до их включения.' }, { title: 'Вопросы', text: 'По вопросам о файлах cookie и хранении данных на сайте пишите на info@trevolalogistics.com.' }], note: 'Этот текст описывает текущий код сайта и требует сверки с окончательными настройками хостинга.' },
      terms: { title: 'Условия использования', sections: [{ title: 'Информация на сайте', text: 'Сайт содержит общую информацию о Trevola Logistics и координации автомобильных перевозок. Сведения не являются обязательной офертой и не подтверждают наличие маршрута, автомобиля или даты.' }, { title: 'Расчёты и бронирование', text: 'Запрос расчёта является обращением за информацией. Объём услуг, цена, вместимость, сроки, требования к обработке груза и договорные условия должны быть подтверждены письменно до принятия бронирования.' }, { title: 'Точность и доступность', text: 'Информация, карты и иллюстрации представлены для общего ознакомления. Маршрут, доступность услуги и организационные условия подтверждаются для каждой перевозки.' }, { title: 'Интеллектуальная собственность и контакты', text: 'Тексты сайта, оформление и материалы бренда Trevola Logistics нельзя копировать или использовать без разрешения правообладателя. Вопросы направляйте на info@trevolalogistics.com.' }, { title: 'Оператор и применимое право', text: 'Оператор сайта — Trevola Logistics, Lda. (португальский налоговый номер (NIF): 516173812). Применимое право и юрисдикцию необходимо подтвердить до окончательной редакции этих условий.' }], note: 'Проект условий · Перед публикацией уточните сведения о компании и юрисдикции.' },
    },
    careers: { emptyTitle: 'Сейчас открытых вакансий нет', emptyText: 'В настоящее время вакансии не опубликованы. Если хотите рассказать о себе для будущих возможностей, напишите нашей команде по электронной почте.', button: 'Связаться с Trevola Logistics' },
    news: { emptyTitle: 'Пока нет новостей', emptyText: 'Сейчас статей нет. Загляните позже, чтобы узнать новости компании и логистической отрасли.' },
    cta: { eyebrow: 'Готовы двигаться дальше?', title: 'Готовы отправить груз?', text: 'Наши специалисты по логистике помогут подобрать подходящее транспортное решение для вашей компании.', quote: 'Запросить расчёт', contact: 'Связаться с нами' },
    seo: { home: ['Trevola Logistics | Автомобильные перевозки по Европе', 'Международные автомобильные перевозки из Португалии в страны Европы с координацией Trevola Logistics.'], 'about-us': ['О компании | Trevola Logistics', 'Trevola Logistics — партнёр по координации автомобильных перевозок из Португалии по Европе.'], services: ['Услуги автоперевозок | Trevola Logistics', 'FTL, LTL, срочные и выделенные автомобильные перевозки по Европе.'], fleet: ['Транспортная сеть | Trevola Logistics', 'Подбор транспортных возможностей с учётом груза, маршрута и сроков.'], industries: ['Отрасли | Trevola Logistics', 'Координация автоперевозок для промышленности, сельского хозяйства, торговли и других отраслей.'], 'request-a-quote': ['Запросить расчёт | Trevola Logistics', 'Укажите маршрут и параметры груза, чтобы запросить расчёт автомобильной перевозки.'], contact: ['Контакты | Trevola Logistics', 'Свяжитесь с Trevola Logistics в Португалии по вопросам международных автоперевозок.'], 'privacy-policy': ['Конфиденциальность | Trevola Logistics', 'Как Trevola Logistics использует данные сайта и запросов на перевозку.'], cookies: ['Файлы cookie | Trevola Logistics', 'Информация о файлах cookie и локальном хранилище браузера на сайте Trevola Logistics.'], terms: ['Условия использования | Trevola Logistics', 'Условия сайта и запросов на координацию автомобильных перевозок Trevola Logistics.'], careers: ['Карьера | Trevola Logistics', 'Вакансии и контактная информация Trevola Logistics.'], news: ['Новости | Trevola Logistics', 'Новости компании и логистики от Trevola Logistics.'] },
  },
  uk: {
    label: 'Українська',
    nav: { home: 'Головна', 'about-us': 'Про компанію', services: 'Послуги', fleet: 'Мережа перевезень', industries: 'Галузі', contact: 'Контакти', careers: 'Кар’єра', news: 'Новини', quote: 'Запросити розрахунок', privacy: 'Конфіденційність', cookies: 'Файли cookie', terms: 'Умови', search: 'Пошук', language: 'Мова' },
    common: { skip: 'Перейти до вмісту', menuOpen: 'Відкрити меню', menuClose: 'Закрити меню', home: 'Головна сторінка Trevola Logistics', searchPlaceholder: 'Пошук послуг, сторінок та інформації', searchClose: 'Закрити пошук', searchEmpty: 'Збігів не знайдено.', searchLabel: 'Пошук на сайті', breadcrumb: 'Головна', footerText: 'Міжнародні автомобільні перевезення з ретельною координацією.', explore: 'Розділи сайту', contact: 'Контакти', rights: 'Усі права захищені.', backTop: 'На початок', email: 'Електронна пошта', phone: 'Телефон', website: 'Сайт', license: 'Ліцензія експедитора', licenseNumber: '№ 901091', whatsappLabel: 'Зв’язатися з Trevola Logistics у WhatsApp', basedPortugal: 'Компанія працює в Португалії', connectedEurope: 'Поєднуємо Португалію з країнами Європи', requestQuote: 'Запросити розрахунок', discuss: 'Обговорити перевезення', mapNote: 'Ілюстративна мапа · доступність маршруту підтверджується для кожного перевезення', portugal: 'Португалія', europe: 'Європа' },
    pages: {
      'about-us': { hero: ['Про Trevola', 'Партнер з автомобільних перевезень', 'із продуманою координацією.', 'Зрозуміла комунікація та практичне планування перевезень між Португалією та Європою.'], heading: ['Завжди на зв’язку', 'Автомобільні перевезення,', 'зрозуміло й надійно.'], paragraphs: ['Trevola Logistics координує міжнародні автомобільні перевезення з Португалії до країн Європи.', 'Ми уважно ставимося до деталей, важливих для перевезення: з’ясовуємо характеристики вантажу, узгоджуємо маршрут і строки та підтримуємо зв’язок на всіх етапах координації.', 'Кожен запит індивідуальний. Ми вислухаємо ваші потреби, розглянемо відповідні варіанти й супроводжуватимемо перевезення від пункту відправлення до доставки.'], cards: [{ title: 'З’ясовуємо потребу', text: 'Спершу уточнюємо вантаж, пункт відправлення і призначення, строки та вимоги до обробки.' }, { title: 'Узгоджуємо план', text: 'Обговорюємо відповідні варіанти автоперевезення й підтверджуємо деталі маршруту.' }, { title: 'Залишаємося на зв’язку', text: 'Під час координації перевезення ви знаєте, до кого звернутися по інформацію.' }] },
      services: { hero: ['Автомобільні перевезення', 'Відповідне рішення', 'для кожного вантажу.', 'Гнучкі варіанти перевезення з урахуванням вантажу, маршруту та строків.'], heading: ['Рішення для автоперевезень', 'Транспорт для', 'вашого вантажу.'], paragraphs: ['Оберіть послугу, щоб обговорити перевезення. Доступність і остаточні умови підтверджуються окремо для кожного запиту.'], cards: [{ icon: 'truck', title: 'Повне завантаження (FTL)', text: 'Окремий автомобіль для повного завантаження, маршрут і строки якого узгоджуємо з урахуванням вашого вантажу.' }, { icon: 'boxes', title: 'Збірний вантаж (LTL)', text: 'Гнучкі варіанти збірного перевезення, коли не потрібен цілий автомобіль.' }, { icon: 'clock', title: 'Термінове перевезення', text: 'Координація термінових вантажів із прямим зв’язком та увагою до погоджених строків.' }, { icon: 'route', title: 'Виділений транспорт', text: 'План перевезення, складений відповідно до конкретних потреб вашого вантажу.' }, { icon: 'globe', title: 'Перевезення Європою', text: 'Координація міжнародних автоперевезень з Португалії до обраних країн Європи.' }, { icon: 'shield', title: 'Логістична координація', text: 'Персональний контакт для супроводу перевезення від пункту відправлення до доставки.' }] },
      fleet: { hero: ['Мережа перевезень', 'Можливості, що', 'допомагають бізнесу зростати.', 'Транспорт підбирається відповідно до потреб кожного перевезення.'], heading: ['Транспортна мережа', 'Гнучкі можливості.', 'Єдиний контакт для зв’язку.'], paragraphs: ['Trevola координує транспортні можливості під конкретне перевезення, а не пропонує одне рішення для всіх.', 'Тип автомобіля, маршрут, умови завантаження та строки обговорюються для кожного запиту. Варіант перевезення підтверджується до бронювання.', 'Trevola Logistics є координатором перевезень і не заявляє, що володіє зображеними автомобілями.'], cards: [{ title: 'Параметри перевезення', text: 'З’ясовуємо габарити й вагу, тип вантажу, місце відправлення та вимоги до доставки.' }, { title: 'Варіант перевезення', text: 'Добираємо місткість автомобіля й маршрут з огляду на вимоги до вантажу.' }, { title: 'Підтвердження деталей', text: 'До початку перевезення погоджуємо з вами строки й організаційні умови.' }] },
      industries: { hero: ['Галузі', 'Перевезення з урахуванням', 'особливостей вашої сфери.', 'Уважно враховуємо вантаж, маршрут і строки в різних галузях.'], heading: ['Галузі', 'Автомобільні перевезення', 'для різних потреб.'], paragraphs: ['Кожна галузь має свої вимоги до перевезення. Ми з’ясовуємо характеристики вантажу, маршрут і строки, а потім обговорюємо відповідний варіант.'], cards: [{ icon: 'car', title: 'Автомобільна промисловість', text: 'Комплектувальні вироби й товари для ланцюгів постачання автомобільної галузі.' }, { icon: 'wheat', title: 'Сільське господарство', text: 'Планування перевезень сільськогосподарської продукції та матеріалів.' }, { icon: 'industry', title: 'Промислове обладнання', text: 'Координація перевезень техніки, деталей і промислового обладнання.' }, { icon: 'cart', title: 'Роздрібна торгівля', text: 'Перевезення товарів для розподілу, поповнення запасів і планування складських залишків.' }, { icon: 'food', title: 'Продукти та напої', text: 'Координація харчових вантажів з урахуванням вимог перевезення.' }, { icon: 'package', title: 'Електронна торгівля', text: 'Варіанти перевезення товарів інтернет-магазинів і потоків замовлень.' }], note: 'Це приклади загальних потреб у перевезенні. Особливі умови обробки, регульовані категорії вантажів і доступність обладнання потрібно підтвердити до бронювання.' },
      contact: { hero: ['Контакти', 'Обговорімо', 'ваше перевезення.', 'Зверніться до Trevola Logistics щодо автомобільних перевезень.'], heading: ['Зв’язатися з Trevola Logistics', 'Обговорімо', 'ваше наступне перевезення.'], paragraphs: ['Наша команда готова обговорити автомобільні перевезення з Португалії до країн Європи.', 'Повідомте пункт відправлення й призначення, параметри вантажу та бажані строки. Ми пояснимо наступні кроки й підкажемо, які дані потрібні для запиту.'] },
    },
    quote: { intro: 'Вкажіть дані про вантаж і маршрут. Це допоможе нашій логістичній команді розглянути відповідний варіант.', fieldsTitle: 'Що потрібно перевезти?', formTitle: 'Деталі перевезення', requiredNote: 'Поля, позначені *, обов’язкові.', labels: { company: 'Назва компанії', contact: 'Контактна особа', email: 'Електронна пошта', phone: 'Телефон', pickupCountry: 'Країна відправлення', pickupCity: 'Місто відправлення', deliveryCountry: 'Країна доставки', deliveryCity: 'Місто доставки', transport: 'Тип перевезення', pallets: 'Кількість палет', cargo: 'Опис вантажу', weight: 'Вага (кг)', volume: 'Об’єм (м³)', loadingDate: 'Бажана дата завантаження', additional: 'Додаткова інформація' }, select: 'Оберіть тип перевезення', errors: { required: 'Заповніть це поле.', email: 'Введіть коректну адресу електронної пошти.', minimum: 'Введіть коректне додатне число.', date: 'Оберіть сьогоднішню або пізнішу дату.', wholeNumber: 'Введіть ціле число.' }, loading: 'Надсилання запиту…', success: 'Дякуємо. Запит на розрахунок надіслано до Trevola Logistics.', notConfigured: 'Онлайн-надсилання ще не налаштовано. Нічого не надіслано. Напишіть на info@trevolalogistics.com.', genericError: 'Не вдалося надіслати запит. Спробуйте ще раз або напишіть на info@trevolalogistics.com.' },
    legal: {
      'privacy-policy': { title: 'Політика конфіденційності', sections: [{ title: 'Контролер персональних даних', text: 'Сайт належить Trevola Logistics, Lda. (португальський податковий номер (NIF): 516173812). З питань конфіденційності пишіть на info@trevolalogistics.com.' }, { title: 'Які дані та з якою метою використовуються', text: 'Коли ви надсилаєте запит на розрахунок, дані форми (компанія й контактна особа, електронна пошта, телефон, маршрут, вантаж, вага/об’єм і бажана дата) використовуються для відповіді та підготовки можливої пропозиції. Постачальник послуг хостингу також може обробляти технічні журнали безпеки.' }, { title: 'Правова підстава та одержувачі', text: 'Запити обробляються для дій на прохання користувача до укладення договору. Повідомлення надсилаються на info@trevolalogistics.com через Resend і корпоративну пошту Zoho. Vercel забезпечує хостинг і серверні функції; Cloudflare обслуговує DNS. Перед публікацією слід уточнити місця обробки даних, перелік субпідрядників і гарантії для можливої міжнародної передачі даних.' }, { title: 'Строк зберігання та ваші права', text: 'Персональні дані із запитів, за якими договір не було укладено, зберігаються один місяць після закриття запиту. Персональні дані клієнтів, потрібні для координації перевезення, і дані кандидатів на вакансії зберігаються один місяць після завершення послуги або розгляду заявки. Бухгалтерські й податкові документи, для яких законом передбачено обов’язкове зберігання, зберігаються протягом установленого законом строку. Відповідно до законодавства про захист персональних даних ви можете запросити доступ, виправлення, видалення або обмеження обробки, заперечити проти обробки та подати скаргу до португальського органу з питань захисту персональних даних CNPD. Для звернення пишіть на info@trevolalogistics.com.' }, { title: 'Оновлення', text: 'До публікації оператор має звірити цей проєкт із юридичними даними компанії, налаштуваннями хостингу й пошти, фактичними строками зберігання та реальними процесами. Після перевірки потрібно оновити дату нижче.' }], note: 'Проєкт для перевірки оператором сайту · Востаннє перевірено 9 жовтня 2026 р.' },
      cookies: { title: 'Політика щодо файлів cookie', sections: [{ title: 'Зберігання даних на сайті', text: 'Сайт не завантажує рекламні чи аналітичні інструменти. Вибрана мова зберігається в локальному сховищі браузера, щоб запам’ятати ваш вибір. Це функціональне налаштування не використовується для реклами чи профілювання.' }, { title: 'Необхідні технології', text: 'Хостинг-платформа може використовувати технічні механізми для роботи й захисту сайту. До публікації оператору слід перевірити практики провайдера щодо зберігання даних і журналів.' }, { title: 'Ваш вибір', text: 'Ви можете видалити збережені мовні налаштування в параметрах даних сайту у браузері. Якщо згодом буде додано аналітичні або маркетингові інструменти, цей текст і механізм згоди потрібно переглянути до їх увімкнення.' }, { title: 'Запитання', text: 'З питаннями про файли cookie чи зберігання даних на сайті пишіть на info@trevolalogistics.com.' }], note: 'Цей текст описує поточний код сайту й потребує звірки з остаточними налаштуваннями хостингу.' },
      terms: { title: 'Умови використання', sections: [{ title: 'Інформація на сайті', text: 'Сайт містить загальну інформацію про Trevola Logistics і координацію автомобільних перевезень. Вміст не є публічною офертою й не підтверджує наявність маршруту, автомобіля або дати.' }, { title: 'Розрахунки й бронювання', text: 'Запит на розрахунок є запитом на інформацію і не є бронюванням. Обсяг послуг, ціна, місткість, строки, вимоги до обробки вантажу й договірні умови потрібно письмово підтвердити до прийняття бронювання.' }, { title: 'Точність і доступність', text: 'Інформація, мапи та ілюстрації наведені для загального ознайомлення. Маршрут, доступність послуги й організаційні умови підтверджуються для кожного перевезення.' }, { title: 'Інтелектуальна власність і контакти', text: 'Тексти сайту, оформлення та матеріали бренду Trevola Logistics не можна копіювати чи використовувати без дозволу правовласника. З питаннями звертайтеся на info@trevolalogistics.com.' }, { title: 'Оператор і застосовне право', text: 'Оператор сайту — Trevola Logistics, Lda. (португальський податковий номер (NIF): 516173812). Застосовне право та юрисдикцію потрібно підтвердити до остаточного затвердження цих умов.' }], note: 'Проєкт умов · Перед публікацією уточніть відомості про компанію та юрисдикцію.' },
    },
    careers: { emptyTitle: 'Наразі відкритих вакансій немає', emptyText: 'Зараз вакансії не опубліковані. Якщо хочете розповісти про себе для майбутніх можливостей, напишіть нашій команді електронною поштою.', button: 'Зв’язатися з Trevola Logistics' },
    news: { emptyTitle: 'Новин поки немає', emptyText: 'Наразі статей немає. Завітайте пізніше, щоб дізнатися новини компанії та логістичної галузі.' },
    cta: { eyebrow: 'Готові рухатися далі?', title: 'Готові перевезти ваш вантаж?', text: 'Наші фахівці з логістики допоможуть знайти відповідне транспортне рішення для вашої компанії.', quote: 'Запросити розрахунок', contact: 'Зв’язатися з нами' },
    seo: { home: ['Trevola Logistics | Автомобільні перевезення Європою', 'Міжнародні автомобільні перевезення з Португалії до країн Європи які координує Trevola Logistics.'], 'about-us': ['Про компанію | Trevola Logistics', 'Trevola Logistics — партнер із координації автомобільних перевезень із Португалії до країн Європи.'], services: ['Послуги автоперевезень | Trevola Logistics', 'FTL, LTL, термінові та виділені автомобільні перевезення Європою.'], fleet: ['Транспортна мережа | Trevola Logistics', 'Транспортні можливості з урахуванням вантажу, маршруту та строків.'], industries: ['Галузі | Trevola Logistics', 'Координація автоперевезень для промисловості, сільського господарства, торгівлі та інших галузей.'], 'request-a-quote': ['Запросити розрахунок | Trevola Logistics', 'Вкажіть маршрут і параметри вантажу, щоб запросити розрахунок автоперевезення.'], contact: ['Контакти | Trevola Logistics', 'Зв’яжіться з Trevola Logistics у Португалії щодо міжнародних автоперевезень.'], 'privacy-policy': ['Конфіденційність | Trevola Logistics', 'Як Trevola Logistics використовує дані сайту та запитів на перевезення.'], cookies: ['Файли cookie | Trevola Logistics', 'Інформація про файли cookie й локальне сховище браузера на сайті Trevola Logistics.'], terms: ['Умови використання | Trevola Logistics', 'Умови сайту й запитів на координацію автомобільних перевезень Trevola Logistics.'], careers: ['Кар’єра | Trevola Logistics', 'Вакансії та контактна інформація Trevola Logistics.'], news: ['Новини | Trevola Logistics', 'Новини компанії та логістики від Trevola Logistics.'] },
  },
}
