import type { Language } from './i18n'

export type PageId = 'home' | 'about-us' | 'services' | 'fleet' | 'industries' | 'request-a-quote' | 'contact' | 'privacy-policy' | 'cookies' | 'terms' | 'careers' | 'news'

type Card = { title: string; text: string; icon?: string }
type PageContent = {
  hero: [string, string, string, string]
  heading?: [string, string, string]
  paragraphs?: string[]
  cards?: Card[]
  note?: string
}
type LocaleContent = {
  label: string
  nav: Record<string, string>
  common: Record<string, string>
  pages: Partial<Record<PageId, PageContent>>
  quote: {
    intro: string; fieldsTitle: string; requiredNote: string; labels: Record<string, string>
    select: string; errors: Record<string, string>; loading: string; success: string; notConfigured: string; genericError: string
  }
  legal: Record<'privacy-policy' | 'cookies' | 'terms', { title: string; sections: Card[]; note: string }>
  careers: { emptyTitle: string; emptyText: string; button: string }
  news: { emptyTitle: string; emptyText: string }
  cta: { eyebrow: string; title: string; text: string; quote: string; contact: string }
  seo: Record<PageId, [string, string]>
}

export const siteCopy: Record<Language, LocaleContent> = {
  en: {
    label: 'English',
    nav: { home: 'Home', 'about-us': 'About Us', services: 'Services', fleet: 'Fleet', industries: 'Industries', contact: 'Contact', careers: 'Careers', news: 'News', quote: 'Request a Quote', privacy: 'Privacy', cookies: 'Cookies', terms: 'Terms', search: 'Search', language: 'Language' },
    common: { skip: 'Skip to content', menuOpen: 'Open menu', menuClose: 'Close menu', home: 'Trevola Logistics home', searchPlaceholder: 'Search services, pages and information', searchClose: 'Close search', searchEmpty: 'No matching pages found.', searchLabel: 'Search this website', breadcrumb: 'Home', footerText: 'International road freight, coordinated with care.', explore: 'Explore', contact: 'Contact', rights: 'All rights reserved.', backTop: 'Back to top', email: 'Email', phone: 'Phone', website: 'Website', license: 'Transport License', licenseNumber: 'No. 901091', whatsappLabel: 'Contact Trevola Logistics on WhatsApp', basedPortugal: 'Based in Portugal', connectedEurope: 'Connected across Europe', requestQuote: 'Request a Quote', discuss: 'Discuss your shipment', mapNote: 'Illustrative map · route availability confirmed per shipment', portugal: 'Portugal', europe: 'Europe' },
    pages: {
      'about-us': { hero: ['About Trevola', 'A road freight partner', 'built on coordination.', 'Clear communication and practical transport planning between Portugal and Europe.'], heading: ['A partner you can reach', 'Road freight,', 'made clearer.'], paragraphs: ['Trevola Logistics coordinates international road transport between Portugal and destinations across Europe.', 'We focus on the details that help a shipment move smoothly: understanding the load, agreeing the route and timing, and keeping communication clear while transport is coordinated.', 'Every request is different. Our role is to listen, identify suitable options and stay close to the details from collection through delivery.'], cards: [{ title: 'Understand the brief', text: 'We start with the cargo, origin, destination, timing and handling requirements.' }, { title: 'Coordinate the plan', text: 'We discuss suitable road transport options and confirm the details for the requested movement.' }, { title: 'Stay connected', text: 'We remain a clear point of contact while the shipment is being coordinated.' }] },
      services: { hero: ['Road Freight Services', 'The right solution', 'for every shipment.', 'Flexible road transport options shaped around your cargo, route and timing.'], heading: ['Road freight solutions', 'Transport shaped', 'around your cargo.'], paragraphs: ['Choose a service to start the conversation. Availability and final arrangements are confirmed for each shipment.'], cards: [{ icon: 'truck', title: 'Full Truck Load (FTL)', text: 'Dedicated vehicle capacity for full loads, planned around the route, cargo requirements and requested delivery window.' }, { icon: 'boxes', title: 'Less Than Truck Load (LTL)', text: 'Part-load and groupage options for shipments that do not require a full vehicle.' }, { icon: 'clock', title: 'Express Road Freight', text: 'Time-sensitive transport coordinated with clear communication and attention to agreed timings.' }, { icon: 'route', title: 'Dedicated Transport', text: 'A focused transport plan shaped around the specific needs of your shipment.' }, { icon: 'globe', title: 'European Road Freight', text: 'International road transport coordination between Portugal and selected European destinations.' }, { icon: 'shield', title: 'Logistics Coordination', text: 'A direct point of contact to coordinate the shipment from collection through delivery.' }] },
      fleet: { hero: ['Fleet & Network', 'Capacity that moves', 'your business forward.', 'Road transport coordinated to match the needs of each shipment.'], heading: ['Fleet & transport network', 'Flexible capacity.', 'One clear contact.'], paragraphs: ['Trevola coordinates road transport capacity to fit the shipment rather than relying on a one-size-fits-all solution.', 'Vehicle type, route, loading requirements and timing are discussed for each request. The available transport arrangement is confirmed before a shipment is booked.', 'Trevola Logistics is presented as a transport coordinator. Vehicle ownership is not claimed.'], cards: [{ title: 'Shipment profile', text: 'We review dimensions, weight, cargo type, collection point and delivery needs.' }, { title: 'Transport option', text: 'Suitable vehicle capacity and route options are discussed against the shipment requirements.' }, { title: 'Confirmed details', text: 'Timing and operational arrangements are confirmed with you before transport proceeds.' }] },
      industries: { hero: ['Industries We Serve', 'Transport shaped', 'around your sector.', 'A considered approach to cargo, route and timing across varied industries.'], heading: ['Industries We Serve', 'Road freight for', 'different demands.'], paragraphs: ['Every sector has its own transport considerations. We begin with the cargo, route and timing, then discuss a suitable road freight option.'], cards: [{ icon: 'car', title: 'Automotive', text: 'Components and goods moving through automotive supply chains.' }, { icon: 'wheat', title: 'Agriculture', text: 'Transport planning for agricultural products and materials.' }, { icon: 'industry', title: 'Industrial Equipment', text: 'Coordination for machinery, parts and industrial equipment.' }, { icon: 'cart', title: 'Retail', text: 'Goods movement for distribution, replenishment and stock planning.' }, { icon: 'food', title: 'Food & Beverage', text: 'Food and beverage cargo coordination based on shipment requirements.' }, { icon: 'package', title: 'E-commerce', text: 'Transport options for online retail goods and fulfilment flows.' }], note: 'These categories are examples of general cargo requirements. Special handling, regulated goods and equipment availability must be confirmed before booking.' },
      contact: { hero: ['Contact', 'Let’s start', 'a conversation.', 'Speak with Trevola Logistics about your road freight requirements.'], heading: ['Contact Trevola Logistics', 'Let’s talk about', 'your next shipment.'], paragraphs: ['Our team is available to discuss road transport between Portugal and European destinations.', 'Share your origin, destination, cargo details and preferred timing. We’ll help you understand the next steps and the information needed to prepare a request.'] },
    },
    quote: { intro: 'Share your cargo and route details. Our logistics team will have the information needed to discuss a suitable solution.', fieldsTitle: 'Tell us what you need to move', requiredNote: 'Fields marked with * are required.', labels: { company: 'Company Name', contact: 'Contact Person', email: 'Email', phone: 'Phone Number', pickupCountry: 'Pickup Country', pickupCity: 'Pickup City', deliveryCountry: 'Delivery Country', deliveryCity: 'Delivery City', transport: 'Type of Transport', pallets: 'Number of Pallets', cargo: 'Cargo Description', weight: 'Weight (kg)', volume: 'Volume (m³)', loadingDate: 'Preferred Loading Date', additional: 'Additional Information' }, select: 'Select transport type', errors: { required: 'Please complete this field.', email: 'Enter a valid email address.', minimum: 'Enter a valid positive number.', date: 'Choose today or a future date.' }, loading: 'Sending request…', success: 'Thank you. Your quote request has been sent to Trevola Logistics.', notConfigured: 'Online quote submission is not configured yet. Nothing was sent. Please email info@trevolalogistics.com.', genericError: 'We could not send your request right now. Please try again or email info@trevolalogistics.com.' },
    legal: {
      'privacy-policy': { title: 'Privacy Policy', sections: [{ title: 'Who is responsible', text: 'The website is operated under the Trevola Logistics brand. Before publication, the operator must insert its full registered legal name and postal address here. For privacy questions, contact info@trevolalogistics.com.' }, { title: 'Information and purposes', text: 'If quote submission is enabled, the form information (company and contact details, route, cargo and loading details) is used to respond to the transport enquiry and prepare a possible quotation. Website security logs may also be processed by the hosting provider.' }, { title: 'Legal basis and recipients', text: 'Enquiry information is processed to take steps requested before entering a contract. Once the email integration is enabled, the message is sent to Trevola Logistics using the configured email delivery provider. The provider, its data-processing terms and any international transfer safeguards must be confirmed before activation.' }, { title: 'Retention and your rights', text: 'The business must set and publish a retention period based on its operational and legal requirements before enabling submissions. Depending on the applicable rules, you may request access, correction, deletion, restriction or object to processing, and may complain to the Portuguese Data Protection Authority (CNPD). Contact info@trevolalogistics.com to exercise a right.' }, { title: 'Updates', text: 'This draft must be reviewed against the actual legal entity, hosting, email provider, retention schedule and processing practices before publication. The date below should be updated after that review.' }], note: 'Draft for completion by the website operator · Last reviewed 4 October 2026' },
      cookies: { title: 'Cookie Policy', sections: [{ title: 'Current website storage', text: 'The current site does not load advertising or analytics tools. It stores your language choice in your browser’s local storage so the selected language can be remembered. This is a functional preference; it is not used for advertising or profiling.' }, { title: 'Essential technologies', text: 'The hosting platform may use technical mechanisms needed to deliver and secure the site. The operator should verify the hosting provider’s own storage and log practices before publication.' }, { title: 'Your choices', text: 'You can remove the saved language preference using your browser’s site-data controls. If optional analytics or marketing technologies are added later, this notice and the consent experience must be reviewed before they are enabled.' }, { title: 'Questions', text: 'For questions about this notice or the site’s storage practices, contact info@trevolalogistics.com.' }], note: 'This notice describes the current site code and must be checked against the final hosting setup.' },
      terms: { title: 'Terms & Conditions', sections: [{ title: 'Website information', text: 'This website provides general information about Trevola Logistics and its road transport coordination services. Content is not a binding offer or confirmation that a route, vehicle or date is available.' }, { title: 'Quotes and bookings', text: 'A request for a quote is an enquiry only. Transport scope, price, capacity, timing, handling requirements and contractual terms must be confirmed in writing before a booking is accepted.' }, { title: 'Accuracy and availability', text: 'Information and illustrative maps or images are provided for general guidance. Actual routes, service availability and operational arrangements are confirmed for each shipment.' }, { title: 'Intellectual property and contact', text: 'Website text, layout and Trevola Logistics brand materials may not be copied or reused without the relevant rights holder’s permission. For questions about these terms, contact info@trevolalogistics.com.' }, { title: 'Operator details and governing law', text: 'The operator must add its registered legal name, postal address and applicable governing-law/jurisdiction details before publication. These draft terms require review for the final business and service arrangements.' }], note: 'Draft terms · Review and complete company and jurisdiction details before publication.' },
    },
    careers: { emptyTitle: 'No open positions right now', emptyText: 'We are not currently listing vacancies. If you would like to introduce yourself for future opportunities, contact our team by email.', button: 'Contact Trevola Logistics' },
    news: { emptyTitle: 'No updates published yet', emptyText: 'There are no news articles to show at the moment. Check back later for company and logistics updates.' },
    cta: { eyebrow: 'Ready to move forward?', title: 'Ready to Move Your Cargo?', text: 'Our logistics experts are ready to provide the best transport solution for your business.', quote: 'Request a Quote', contact: 'Contact Us' },
    seo: {
      home: ['Trevola Logistics | European Road Freight', 'International road freight between Portugal and European destinations, coordinated by Trevola Logistics.'],
      'about-us': ['About Us | Trevola Logistics', 'Meet Trevola Logistics, a Portugal-based partner for coordinated road freight across Europe.'],
      services: ['Road Freight Services | Trevola Logistics', 'Explore FTL, LTL, express and dedicated road transport coordination for European shipments.'],
      fleet: ['Fleet & Network | Trevola Logistics', 'Road transport capacity coordinated around shipment requirements, routes and timing.'],
      industries: ['Industries We Serve | Trevola Logistics', 'Road freight coordination for automotive, agriculture, retail, food and other industries.'],
      'request-a-quote': ['Request a Quote | Trevola Logistics', 'Share your route and cargo details to request a Trevola Logistics road freight quotation.'],
      contact: ['Contact | Trevola Logistics', 'Contact Trevola Logistics in Portugal about international road freight and shipment requirements.'],
      'privacy-policy': ['Privacy Policy | Trevola Logistics', 'How Trevola Logistics handles website and transport enquiry information.'],
      cookies: ['Cookie Policy | Trevola Logistics', 'Information about cookies and browser storage used by the Trevola Logistics website.'],
      terms: ['Terms & Conditions | Trevola Logistics', 'Website and enquiry terms for Trevola Logistics road transport coordination.'],
      careers: ['Careers | Trevola Logistics', 'Career opportunities and contact information for Trevola Logistics.'],
      news: ['News | Trevola Logistics', 'Company and logistics updates from Trevola Logistics.'],
    },
  },
  pt: {
    label: 'Português',
    nav: { home: 'Início', 'about-us': 'Sobre nós', services: 'Serviços', fleet: 'Rede', industries: 'Indústrias', contact: 'Contactos', careers: 'Carreiras', news: 'Notícias', quote: 'Pedir orçamento', privacy: 'Privacidade', cookies: 'Cookies', terms: 'Termos', search: 'Pesquisar', language: 'Idioma' },
    common: { skip: 'Saltar para o conteúdo', menuOpen: 'Abrir menu', menuClose: 'Fechar menu', home: 'Página inicial Trevola Logistics', searchPlaceholder: 'Pesquisar serviços, páginas e informações', searchClose: 'Fechar pesquisa', searchEmpty: 'Não foram encontradas páginas correspondentes.', searchLabel: 'Pesquisar neste website', breadcrumb: 'Início', footerText: 'Transporte rodoviário internacional, coordenado com cuidado.', explore: 'Explorar', contact: 'Contactos', rights: 'Todos os direitos reservados.', backTop: 'Voltar ao topo', email: 'Email', phone: 'Telefone', website: 'Website', license: 'Alvará Transitário', licenseNumber: 'Nº 901091', whatsappLabel: 'Contactar a Trevola Logistics pelo WhatsApp', basedPortugal: 'Sediados em Portugal', connectedEurope: 'Ligados a destinos europeus', requestQuote: 'Pedir orçamento', discuss: 'Fale sobre a sua expedição', mapNote: 'Mapa ilustrativo · disponibilidade confirmada para cada expedição', portugal: 'Portugal', europe: 'Europa' },
    pages: {
      'about-us': { hero: ['Sobre a Trevola', 'Um parceiro de transporte', 'com coordenação cuidada.', 'Comunicação clara e planeamento rodoviário entre Portugal e a Europa.'], heading: ['Um parceiro próximo', 'Transporte rodoviário,', 'com clareza.'], paragraphs: ['A Trevola Logistics coordena transporte rodoviário internacional entre Portugal e destinos europeus.', 'Acompanhamos os detalhes que ajudam uma expedição a decorrer com clareza: carga, percurso, prazos e comunicação durante a coordenação.', 'Cada pedido é diferente. Ouvimos as necessidades, analisamos opções e acompanhamos a expedição desde a recolha até à entrega.'], cards: [{ title: 'Compreender o pedido', text: 'Começamos pela carga, origem, destino, prazo e requisitos de manuseamento.' }, { title: 'Coordenar o plano', text: 'Analisamos opções rodoviárias adequadas e confirmamos os detalhes do transporte solicitado.' }, { title: 'Manter o contacto', text: 'Mantemos um ponto de contacto claro enquanto a expedição é coordenada.' }] },
      services: { hero: ['Serviços rodoviários', 'A solução certa', 'para cada expedição.', 'Opções flexíveis de transporte rodoviário ajustadas à carga, ao percurso e ao prazo.'], heading: ['Soluções rodoviárias', 'Transporte pensado', 'para a sua carga.'], paragraphs: ['Escolha um serviço para iniciar a conversa. A disponibilidade e os detalhes finais são confirmados para cada expedição.'], cards: [{ icon: 'truck', title: 'Carga completa (FTL)', text: 'Capacidade dedicada para cargas completas, planeada conforme o percurso, a mercadoria e o prazo solicitado.' }, { icon: 'boxes', title: 'Carga parcial (LTL)', text: 'Opções de grupagem para expedições que não precisam de um veículo completo.' }, { icon: 'clock', title: 'Transporte expresso', text: 'Transporte urgente coordenado com comunicação clara e atenção aos prazos acordados.' }, { icon: 'route', title: 'Transporte dedicado', text: 'Um plano de transporte ajustado às necessidades específicas da sua expedição.' }, { icon: 'globe', title: 'Transporte rodoviário europeu', text: 'Coordenação de transporte internacional entre Portugal e destinos europeus selecionados.' }, { icon: 'shield', title: 'Coordenação logística', text: 'Um contacto direto para coordenar a expedição desde a recolha até à entrega.' }] },
      fleet: { hero: ['Frota e rede', 'Capacidade que faz', 'o negócio avançar.', 'Transporte coordenado de acordo com as necessidades de cada expedição.'], heading: ['Frota e rede de transporte', 'Capacidade flexível.', 'Um contacto claro.'], paragraphs: ['A Trevola coordena capacidade de transporte rodoviário de acordo com cada expedição.', 'O tipo de veículo, percurso, requisitos de carga e prazos são analisados em cada pedido. A solução disponível é confirmada antes da reserva.', 'A Trevola Logistics é apresentada como coordenadora de transporte; não declara ser proprietária dos veículos ilustrados.'], cards: [{ title: 'Perfil da expedição', text: 'Analisamos dimensões, peso, tipo de mercadoria, local de recolha e entrega.' }, { title: 'Opção de transporte', text: 'As opções de capacidade e percurso são avaliadas segundo os requisitos da carga.' }, { title: 'Detalhes confirmados', text: 'Os prazos e procedimentos são confirmados antes de o transporte avançar.' }] },
      industries: { hero: ['Setores que apoiamos', 'Transporte ajustado', 'ao seu setor.', 'Uma abordagem cuidada à carga, ao percurso e aos prazos de vários setores.'], heading: ['Setores que apoiamos', 'Transporte rodoviário para', 'diferentes necessidades.'], paragraphs: ['Cada setor tem requisitos próprios. Começamos pela carga, percurso e prazo para analisar uma solução rodoviária adequada.'], cards: [{ icon: 'car', title: 'Automóvel', text: 'Componentes e mercadorias para cadeias de fornecimento automóvel.' }, { icon: 'wheat', title: 'Agricultura', text: 'Planeamento de transporte para produtos e materiais agrícolas.' }, { icon: 'industry', title: 'Equipamento industrial', text: 'Coordenação para máquinas, peças e equipamento industrial.' }, { icon: 'cart', title: 'Retalho', text: 'Transporte de mercadorias para distribuição, reposição e gestão de stock.' }, { icon: 'food', title: 'Alimentação e bebidas', text: 'Coordenação de cargas alimentares conforme os requisitos da expedição.' }, { icon: 'package', title: 'Comércio eletrónico', text: 'Opções de transporte para mercadorias e fluxos de comércio online.' }], note: 'Estas categorias são exemplos de necessidades gerais. Requisitos especiais, mercadorias reguladas e disponibilidade de equipamento devem ser confirmados antes da reserva.' },
      contact: { hero: ['Contactos', 'Vamos iniciar', 'uma conversa.', 'Fale com a Trevola Logistics sobre as suas necessidades de transporte.'], heading: ['Contacte a Trevola Logistics', 'Vamos falar sobre', 'a sua próxima carga.'], paragraphs: ['A nossa equipa está disponível para conversar sobre transporte rodoviário entre Portugal e destinos europeus.', 'Partilhe a origem, o destino, os detalhes da carga e o prazo pretendido. Ajudamos a esclarecer os próximos passos para preparar o pedido.'] },
    },
    quote: { intro: 'Partilhe os detalhes da carga e do percurso. A nossa equipa terá a informação necessária para analisar uma solução adequada.', fieldsTitle: 'O que precisa de transportar?', requiredNote: 'Os campos assinalados com * são obrigatórios.', labels: { company: 'Nome da empresa', contact: 'Pessoa de contacto', email: 'Email', phone: 'Número de telefone', pickupCountry: 'País de recolha', pickupCity: 'Cidade de recolha', deliveryCountry: 'País de entrega', deliveryCity: 'Cidade de entrega', transport: 'Tipo de transporte', pallets: 'Número de paletes', cargo: 'Descrição da carga', weight: 'Peso (kg)', volume: 'Volume (m³)', loadingDate: 'Data preferencial de carga', additional: 'Informações adicionais' }, select: 'Selecione o tipo de transporte', errors: { required: 'Preencha este campo.', email: 'Introduza um endereço de email válido.', minimum: 'Introduza um número positivo válido.', date: 'Escolha hoje ou uma data futura.' }, loading: 'A enviar o pedido…', success: 'Obrigado. O seu pedido de orçamento foi enviado à Trevola Logistics.', notConfigured: 'O envio online ainda não está configurado. Nada foi enviado. Contacte info@trevolalogistics.com.', genericError: 'Não foi possível enviar o pedido agora. Tente novamente ou contacte info@trevolalogistics.com.' },
    legal: {
      'privacy-policy': { title: 'Política de Privacidade', sections: [{ title: 'Responsável pelo tratamento', text: 'O website é operado sob a marca Trevola Logistics. Antes da publicação, o operador deve inserir aqui a denominação social completa e a morada registada. Para questões de privacidade, contacte info@trevolalogistics.com.' }, { title: 'Informação e finalidades', text: 'Quando o envio de pedidos de orçamento estiver ativo, os dados do formulário (empresa, contacto, percurso, carga e data) serão usados para responder ao pedido e preparar uma proposta de transporte. O alojamento pode também tratar registos técnicos de segurança.' }, { title: 'Fundamento e destinatários', text: 'Os dados do pedido são tratados para diligências pré-contratuais solicitadas. Quando a integração de email for ativada, a mensagem será enviada à Trevola Logistics através do fornecedor de email configurado. O fornecedor, os respetivos termos de tratamento e as salvaguardas para eventuais transferências internacionais devem ser confirmados antes da ativação.' }, { title: 'Conservação e direitos', text: 'A empresa deve definir e publicar um prazo de conservação compatível com os requisitos operacionais e legais antes de ativar o envio. Consoante as regras aplicáveis, poderá solicitar acesso, retificação, apagamento, limitação ou opor-se ao tratamento, e apresentar reclamação à CNPD. Contacte info@trevolalogistics.com para exercer os seus direitos.' }, { title: 'Revisões', text: 'Este modelo deve ser revisto de acordo com a entidade legal, alojamento, fornecedor de email, prazo de conservação e práticas reais. Atualize a data após essa revisão.' }], note: 'Modelo a completar pelo operador do website · Revisto em 4 de outubro de 2026' },
      cookies: { title: 'Política de Cookies', sections: [{ title: 'Armazenamento utilizado atualmente', text: 'O website atual não carrega ferramentas de publicidade ou analítica. Guarda a preferência de idioma no armazenamento local do navegador para memorizar a escolha. Esta preferência funcional não é usada para publicidade nem definição de perfis.' }, { title: 'Tecnologias essenciais', text: 'A plataforma de alojamento poderá usar mecanismos técnicos necessários para disponibilizar e proteger o website. O operador deve confirmar as práticas do fornecedor antes da publicação.' }, { title: 'As suas opções', text: 'Pode remover a preferência de idioma nas definições de dados do website do seu navegador. Se forem acrescentadas ferramentas opcionais de analítica ou marketing, este aviso e a experiência de consentimento devem ser revistos antes da ativação.' }, { title: 'Contactos', text: 'Para questões sobre este aviso ou as tecnologias de armazenamento, contacte info@trevolalogistics.com.' }], note: 'Este aviso descreve o código atual e deve ser confirmado face à configuração final do alojamento.' },
      terms: { title: 'Termos e Condições', sections: [{ title: 'Informação do website', text: 'Este website apresenta informação geral sobre a Trevola Logistics e a coordenação de transporte rodoviário. O conteúdo não constitui uma proposta vinculativa nem confirma a disponibilidade de percurso, veículo ou data.' }, { title: 'Orçamentos e reservas', text: 'Um pedido de orçamento é apenas uma consulta. O âmbito, preço, capacidade, prazo, requisitos de manuseamento e condições contratuais devem ser confirmados por escrito antes de qualquer reserva.' }, { title: 'Precisão e disponibilidade', text: 'A informação, os mapas e as imagens ilustrativas destinam-se a orientação geral. Os percursos, a disponibilidade e os procedimentos são confirmados para cada expedição.' }, { title: 'Propriedade intelectual e contacto', text: 'Os textos, o layout e os materiais de marca não podem ser copiados ou reutilizados sem autorização dos respetivos titulares. Para questões, contacte info@trevolalogistics.com.' }, { title: 'Identificação e lei aplicável', text: 'O operador deve inserir a denominação social registada, morada e detalhes da lei/jurisdição aplicável antes da publicação. Estes termos precisam de revisão para corresponder à empresa e aos serviços finais.' }], note: 'Modelo de termos · Complete e reveja os dados da empresa e jurisdição antes da publicação.' },
    },
    careers: { emptyTitle: 'Não temos vagas abertas neste momento', emptyText: 'Não existem vagas publicadas atualmente. Se quiser apresentar o seu perfil para oportunidades futuras, contacte a nossa equipa por email.', button: 'Contactar a Trevola Logistics' },
    news: { emptyTitle: 'Ainda não há notícias publicadas', emptyText: 'Neste momento não existem artigos publicados. Volte mais tarde para acompanhar novidades da empresa e do setor logístico.' },
    cta: { eyebrow: 'Pronto para avançar?', title: 'Pronto para transportar a sua carga?', text: 'Os nossos especialistas em logística estão prontos para encontrar a melhor solução de transporte para a sua empresa.', quote: 'Pedir orçamento', contact: 'Contactar' },
    seo: {
      home: ['Trevola Logistics | Transporte Rodoviário Europeu', 'Transporte rodoviário internacional entre Portugal e destinos europeus, coordenado pela Trevola Logistics.'],
      'about-us': ['Sobre Nós | Trevola Logistics', 'Conheça a Trevola Logistics, parceira sediada em Portugal para coordenação de transporte rodoviário europeu.'],
      services: ['Serviços de Transporte | Trevola Logistics', 'Conheça opções de transporte rodoviário FTL, LTL, expresso e dedicado para expedições europeias.'],
      fleet: ['Frota e Rede | Trevola Logistics', 'Capacidade de transporte rodoviário coordenada conforme a carga, o percurso e o prazo.'],
      industries: ['Setores | Trevola Logistics', 'Coordenação rodoviária para os setores automóvel, agrícola, retalho, alimentar e outros.'],
      'request-a-quote': ['Pedir Orçamento | Trevola Logistics', 'Partilhe o percurso e os detalhes da carga para pedir um orçamento de transporte rodoviário.'],
      contact: ['Contactos | Trevola Logistics', 'Contacte a Trevola Logistics em Portugal sobre transporte rodoviário internacional.'],
      'privacy-policy': ['Política de Privacidade | Trevola Logistics', 'Saiba como a Trevola Logistics trata dados do website e pedidos de transporte.'],
      cookies: ['Política de Cookies | Trevola Logistics', 'Informação sobre cookies e armazenamento do navegador usados pelo website Trevola Logistics.'],
      terms: ['Termos e Condições | Trevola Logistics', 'Termos do website e dos pedidos de coordenação de transporte rodoviário.'],
      careers: ['Carreiras | Trevola Logistics', 'Oportunidades profissionais e contactos da Trevola Logistics.'],
      news: ['Notícias | Trevola Logistics', 'Novidades da empresa e do setor logístico da Trevola Logistics.'],
    },
  },
  de: {
    label: 'Deutsch',
    nav: { home: 'Startseite', 'about-us': 'Über uns', services: 'Leistungen', fleet: 'Netzwerk', industries: 'Branchen', contact: 'Kontakt', careers: 'Karriere', news: 'Neuigkeiten', quote: 'Angebot anfragen', privacy: 'Datenschutz', cookies: 'Cookies', terms: 'AGB', search: 'Suche', language: 'Sprache' },
    common: { skip: 'Zum Inhalt springen', menuOpen: 'Menü öffnen', menuClose: 'Menü schließen', home: 'Trevola Logistics Startseite', searchPlaceholder: 'Leistungen, Seiten und Informationen suchen', searchClose: 'Suche schließen', searchEmpty: 'Keine passenden Seiten gefunden.', searchLabel: 'Diese Website durchsuchen', breadcrumb: 'Startseite', footerText: 'Internationaler Straßengüterverkehr, sorgfältig koordiniert.', explore: 'Entdecken', contact: 'Kontakt', rights: 'Alle Rechte vorbehalten.', backTop: 'Nach oben', email: 'E-Mail', phone: 'Telefon', website: 'Website', license: 'Speditionslizenz', licenseNumber: 'Nr. 901091', whatsappLabel: 'Trevola Logistics per WhatsApp kontaktieren', basedPortugal: 'In Portugal ansässig', connectedEurope: 'Mit Europa verbunden', requestQuote: 'Angebot anfragen', discuss: 'Sendung besprechen', mapNote: 'Illustrative Karte · Verfügbarkeit je Sendung bestätigen', portugal: 'Portugal', europe: 'Europa' },
    pages: {
      'about-us': { hero: ['Über Trevola', 'Ein Straßengüterverkehrspartner', 'mit klarer Koordination.', 'Klare Kommunikation und praktische Transportplanung zwischen Portugal und Europa.'], heading: ['Ein erreichbarer Partner', 'Straßentransport,', 'klar koordiniert.'], paragraphs: ['Trevola Logistics koordiniert internationalen Straßentransport zwischen Portugal und europäischen Zielen.', 'Wir achten auf die Details einer reibungslosen Sendung: Fracht, Route, Zeitplan und klare Kommunikation während der Koordination.', 'Jede Anfrage ist anders. Wir hören zu, prüfen passende Optionen und begleiten die Sendung von der Abholung bis zur Zustellung.'], cards: [{ title: 'Anforderungen verstehen', text: 'Wir beginnen mit Fracht, Start, Ziel, Zeitplan und Handhabungsanforderungen.' }, { title: 'Plan koordinieren', text: 'Wir besprechen geeignete Straßenverkehrsoptionen und bestätigen die angefragten Details.' }, { title: 'In Kontakt bleiben', text: 'Während der Koordination bleiben wir Ihr klarer Ansprechpartner.' }] },
      services: { hero: ['Straßentransport', 'Die passende Lösung', 'für jede Sendung.', 'Flexible Transportoptionen, abgestimmt auf Fracht, Route und Zeitplan.'], heading: ['Straßentransportlösungen', 'Transport passend', 'zu Ihrer Fracht.'], paragraphs: ['Wählen Sie einen Service, um Ihre Anfrage zu besprechen. Verfügbarkeit und Ablauf werden für jede Sendung bestätigt.'], cards: [{ icon: 'truck', title: 'Komplettladung (FTL)', text: 'Dedizierte Fahrzeugkapazität für Komplettladungen, passend zu Route, Fracht und Lieferzeit.' }, { icon: 'boxes', title: 'Teilladung (LTL)', text: 'Sammelgutoptionen für Sendungen, die kein ganzes Fahrzeug benötigen.' }, { icon: 'clock', title: 'Express-Transport', text: 'Zeitkritische Transporte mit klarer Kommunikation und Blick auf vereinbarte Termine.' }, { icon: 'route', title: 'Dedizierter Transport', text: 'Ein Transportplan passend zu den besonderen Anforderungen Ihrer Sendung.' }, { icon: 'globe', title: 'Europaweiter Straßentransport', text: 'Koordination internationaler Transporte zwischen Portugal und ausgewählten europäischen Zielen.' }, { icon: 'shield', title: 'Logistikkoordination', text: 'Ein direkter Ansprechpartner für die Koordination von Abholung bis Zustellung.' }] },
      fleet: { hero: ['Flotte und Netzwerk', 'Kapazität, die Ihr', 'Geschäft voranbringt.', 'Transportkoordination passend zu den Anforderungen jeder Sendung.'], heading: ['Flotte und Transportnetzwerk', 'Flexible Kapazität.', 'Ein klarer Kontakt.'], paragraphs: ['Trevola koordiniert Transportkapazitäten passend zur jeweiligen Sendung.', 'Fahrzeugtyp, Route, Ladeanforderungen und Zeitplan werden für jede Anfrage besprochen. Die verfügbare Lösung wird vor der Buchung bestätigt.', 'Trevola Logistics wird als Transportkoordinator dargestellt und beansprucht kein Eigentum an den abgebildeten Fahrzeugen.'], cards: [{ title: 'Sendungsprofil', text: 'Wir prüfen Maße, Gewicht, Frachtart sowie Abhol- und Lieferort.' }, { title: 'Transportoption', text: 'Passende Kapazität und Routen werden anhand der Anforderungen besprochen.' }, { title: 'Bestätigte Details', text: 'Zeitplan und Ablauf werden vor Transportbeginn mit Ihnen bestätigt.' }] },
      industries: { hero: ['Branchen', 'Transport passend', 'zu Ihrer Branche.', 'Ein durchdachter Umgang mit Fracht, Route und Zeitplan für verschiedene Branchen.'], heading: ['Branchen, die wir unterstützen', 'Straßentransport für', 'unterschiedliche Anforderungen.'], paragraphs: ['Jede Branche hat eigene Transportanforderungen. Wir betrachten Fracht, Route und Zeitplan und besprechen eine passende Lösung.'], cards: [{ icon: 'car', title: 'Automobil', text: 'Komponenten und Waren für Lieferketten der Automobilindustrie.' }, { icon: 'wheat', title: 'Landwirtschaft', text: 'Transportplanung für landwirtschaftliche Produkte und Materialien.' }, { icon: 'industry', title: 'Industrieausrüstung', text: 'Koordination von Maschinen, Teilen und industrieller Ausrüstung.' }, { icon: 'cart', title: 'Einzelhandel', text: 'Warentransport für Distribution, Nachschub und Bestandsplanung.' }, { icon: 'food', title: 'Lebensmittel und Getränke', text: 'Koordination von Lebensmittelfracht nach den Anforderungen der Sendung.' }, { icon: 'package', title: 'E-Commerce', text: 'Transportoptionen für Online-Handelswaren und Warenflüsse.' }], note: 'Die Kategorien zeigen allgemeine Frachtanforderungen. Sonderbehandlung, regulierte Waren und Ausrüstung müssen vor der Buchung bestätigt werden.' },
      contact: { hero: ['Kontakt', 'Lassen Sie uns', 'ins Gespräch kommen.', 'Sprechen Sie mit Trevola Logistics über Ihre Transportanforderungen.'], heading: ['Trevola Logistics kontaktieren', 'Sprechen wir über', 'Ihre nächste Sendung.'], paragraphs: ['Unser Team bespricht Straßentransporte zwischen Portugal und europäischen Zielen.', 'Teilen Sie Start, Ziel, Frachtdetails und gewünschten Zeitplan mit. Wir erläutern die nächsten Schritte für Ihre Anfrage.'] },
    },
    quote: { intro: 'Teilen Sie uns Fracht- und Routendetails mit. Unser Team erhält so die nötigen Informationen, um eine passende Lösung zu besprechen.', fieldsTitle: 'Was möchten Sie transportieren?', requiredNote: 'Mit * markierte Felder sind Pflichtfelder.', labels: { company: 'Unternehmen', contact: 'Ansprechpartner', email: 'E-Mail', phone: 'Telefonnummer', pickupCountry: 'Abholland', pickupCity: 'Abholort', deliveryCountry: 'Zielland', deliveryCity: 'Lieferort', transport: 'Transportart', pallets: 'Anzahl Paletten', cargo: 'Frachtbeschreibung', weight: 'Gewicht (kg)', volume: 'Volumen (m³)', loadingDate: 'Gewünschtes Ladedatum', additional: 'Zusätzliche Informationen' }, select: 'Transportart wählen', errors: { required: 'Bitte füllen Sie dieses Feld aus.', email: 'Bitte geben Sie eine gültige E-Mail-Adresse ein.', minimum: 'Bitte geben Sie eine gültige positive Zahl ein.', date: 'Wählen Sie heute oder ein zukünftiges Datum.' }, loading: 'Anfrage wird gesendet…', success: 'Vielen Dank. Ihre Angebotsanfrage wurde an Trevola Logistics gesendet.', notConfigured: 'Der Online-Versand ist noch nicht eingerichtet. Es wurde nichts gesendet. Bitte schreiben Sie an info@trevolalogistics.com.', genericError: 'Die Anfrage konnte gerade nicht gesendet werden. Bitte versuchen Sie es erneut oder schreiben Sie an info@trevolalogistics.com.' },
    legal: {
      'privacy-policy': { title: 'Datenschutzerklärung', sections: [{ title: 'Verantwortliche Stelle', text: 'Die Website wird unter der Marke Trevola Logistics betrieben. Vor der Veröffentlichung muss der Betreiber hier den vollständigen eingetragenen Firmennamen und die Postanschrift angeben. Datenschutzfragen: info@trevolalogistics.com.' }, { title: 'Daten und Zwecke', text: 'Wenn Angebotsanfragen aktiviert sind, werden Formularangaben zu Unternehmen, Kontakt, Route, Fracht und Ladezeitpunkt zur Beantwortung der Anfrage und Erstellung eines möglichen Transportangebots verwendet. Der Hosting-Anbieter kann technische Sicherheitsprotokolle verarbeiten.' }, { title: 'Rechtsgrundlage und Empfänger', text: 'Anfragedaten werden für vorvertragliche Schritte auf Wunsch der anfragenden Person verarbeitet. Nach Aktivierung der E-Mail-Integration wird die Nachricht über den konfigurierten E-Mail-Anbieter an Trevola Logistics übermittelt. Anbieter, Auftragsverarbeitungsbedingungen und Garantien für etwaige internationale Übermittlungen sind vor Aktivierung zu prüfen.' }, { title: 'Speicherung und Rechte', text: 'Das Unternehmen muss vor Aktivierung eine angemessene Speicherfrist anhand seiner betrieblichen und gesetzlichen Anforderungen festlegen und veröffentlichen. Je nach geltendem Recht können Sie Auskunft, Berichtigung, Löschung oder Einschränkung verlangen, Widerspruch einlegen und sich bei der portugiesischen Datenschutzbehörde CNPD beschweren. Kontakt: info@trevolalogistics.com.' }, { title: 'Aktualisierung', text: 'Dieser Entwurf muss mit der tatsächlichen Gesellschaft, dem Hosting, E-Mail-Anbieter, Speicherfristen und Verarbeitungspraktiken abgeglichen werden. Das Datum nach der Prüfung aktualisieren.' }], note: 'Entwurf zur Ergänzung durch den Websitebetreiber · Geprüft am 4. Oktober 2026' },
      cookies: { title: 'Cookie-Richtlinie', sections: [{ title: 'Aktuelle Speicherung', text: 'Die Website lädt derzeit keine Werbe- oder Analysetools. Die gewählte Sprache wird im lokalen Browserspeicher gespeichert, damit die Einstellung erhalten bleibt. Diese funktionale Präferenz dient weder Werbung noch Profilbildung.' }, { title: 'Notwendige Technologien', text: 'Der Hosting-Anbieter kann technische Funktionen verwenden, die für Bereitstellung und Sicherheit der Website erforderlich sind. Der Betreiber sollte dessen Speicher- und Protokollierungspraxis vor Veröffentlichung prüfen.' }, { title: 'Ihre Optionen', text: 'Die gespeicherte Sprachpräferenz lässt sich über die Website-Dateneinstellungen des Browsers entfernen. Werden später optionale Analyse- oder Marketingdienste ergänzt, müssen Hinweis und Einwilligungsablauf vor deren Aktivierung geprüft werden.' }, { title: 'Kontakt', text: 'Fragen zu diesem Hinweis oder den Speichertechnologien richten Sie an info@trevolalogistics.com.' }], note: 'Dieser Hinweis beschreibt den aktuellen Website-Code und muss mit dem endgültigen Hosting abgeglichen werden.' },
      terms: { title: 'Allgemeine Geschäftsbedingungen', sections: [{ title: 'Website-Informationen', text: 'Diese Website enthält allgemeine Informationen über Trevola Logistics und die Koordination von Straßentransporten. Inhalte sind kein verbindliches Angebot und bestätigen nicht die Verfügbarkeit einer Route, eines Fahrzeugs oder eines Termins.' }, { title: 'Angebote und Buchungen', text: 'Eine Angebotsanfrage ist zunächst unverbindlich. Umfang, Preis, Kapazität, Zeitplan, Handhabung und Vertragsbedingungen müssen vor einer Buchung schriftlich bestätigt werden.' }, { title: 'Richtigkeit und Verfügbarkeit', text: 'Angaben, Karten und illustrative Bilder dienen der allgemeinen Orientierung. Routen, Verfügbarkeit und Ablauf werden für jede Sendung bestätigt.' }, { title: 'Geistiges Eigentum und Kontakt', text: 'Website-Texte, Layout und Markenmaterialien dürfen ohne Genehmigung der Rechteinhaber nicht kopiert oder wiederverwendet werden. Fragen: info@trevolalogistics.com.' }, { title: 'Betreiber und anwendbares Recht', text: 'Vor Veröffentlichung sind vollständiger Firmenname, Anschrift sowie Angaben zu anwendbarem Recht und Gerichtsstand einzutragen. Diese Bedingungen müssen für das endgültige Unternehmen und Angebot geprüft werden.' }], note: 'Entwurf · Unternehmens- und Gerichtsstandangaben vor Veröffentlichung ergänzen.' },
    },
    careers: { emptyTitle: 'Derzeit keine offenen Stellen', emptyText: 'Aktuell sind keine Stellen ausgeschrieben. Wenn Sie sich für zukünftige Möglichkeiten vorstellen möchten, schreiben Sie unserem Team per E-Mail.', button: 'Trevola Logistics kontaktieren' },
    news: { emptyTitle: 'Noch keine Neuigkeiten veröffentlicht', emptyText: 'Zurzeit gibt es keine Artikel. Besuchen Sie uns später wieder für Neuigkeiten aus dem Unternehmen und der Logistikbranche.' },
    cta: { eyebrow: 'Bereit für den nächsten Schritt?', title: 'Bereit, Ihre Fracht zu bewegen?', text: 'Unsere Logistikexperten finden die passende Transportlösung für Ihr Unternehmen.', quote: 'Angebot anfragen', contact: 'Kontakt aufnehmen' },
    seo: {
      home: ['Trevola Logistics | Europäischer Straßentransport', 'Internationaler Straßengüterverkehr zwischen Portugal und europäischen Zielen, koordiniert von Trevola Logistics.'],
      'about-us': ['Über uns | Trevola Logistics', 'Trevola Logistics ist ein portugiesischer Partner für koordinierten Straßentransport in Europa.'],
      services: ['Straßentransport | Trevola Logistics', 'FTL-, LTL-, Express- und dedizierte Transportkoordination für europäische Sendungen.'],
      fleet: ['Flotte und Netzwerk | Trevola Logistics', 'Transportkapazität passend zu Frachtanforderungen, Routen und Zeitplänen.'],
      industries: ['Branchen | Trevola Logistics', 'Straßentransportkoordination für Automobil, Landwirtschaft, Einzelhandel, Lebensmittel und weitere Branchen.'],
      'request-a-quote': ['Angebot anfragen | Trevola Logistics', 'Fracht- und Routendetails für eine Straßentransportanfrage an Trevola Logistics teilen.'],
      contact: ['Kontakt | Trevola Logistics', 'Kontaktieren Sie Trevola Logistics in Portugal zu internationalem Straßentransport.'],
      'privacy-policy': ['Datenschutz | Trevola Logistics', 'Informationen zur Verarbeitung von Website- und Transportanfragedaten durch Trevola Logistics.'],
      cookies: ['Cookies | Trevola Logistics', 'Informationen zu Cookies und Browser-Speicherung auf der Trevola Logistics Website.'],
      terms: ['AGB | Trevola Logistics', 'Website- und Anfragebedingungen für die Straßentransportkoordination von Trevola Logistics.'],
      careers: ['Karriere | Trevola Logistics', 'Karriere und Kontaktinformationen von Trevola Logistics.'],
      news: ['Neuigkeiten | Trevola Logistics', 'Unternehmens- und Logistikneuigkeiten von Trevola Logistics.'],
    },
  },
  fr: {
    label: 'Français',
    nav: { home: 'Accueil', 'about-us': 'À propos', services: 'Services', fleet: 'Réseau', industries: 'Secteurs', contact: 'Contact', careers: 'Carrières', news: 'Actualités', quote: 'Demander un devis', privacy: 'Confidentialité', cookies: 'Cookies', terms: 'Conditions', search: 'Rechercher', language: 'Langue' },
    common: { skip: 'Aller au contenu', menuOpen: 'Ouvrir le menu', menuClose: 'Fermer le menu', home: 'Accueil Trevola Logistics', searchPlaceholder: 'Rechercher des services et des informations', searchClose: 'Fermer la recherche', searchEmpty: 'Aucune page correspondante.', searchLabel: 'Rechercher sur ce site', breadcrumb: 'Accueil', footerText: 'Transport routier international, coordonné avec soin.', explore: 'Explorer', contact: 'Contact', rights: 'Tous droits réservés.', backTop: 'Retour en haut', email: 'E-mail', phone: 'Téléphone', website: 'Site web', license: 'Licence de commissionnaire de transport', licenseNumber: 'N° 901091', whatsappLabel: 'Contacter Trevola Logistics sur WhatsApp', basedPortugal: 'Basés au Portugal', connectedEurope: 'Connectés à l’Europe', requestQuote: 'Demander un devis', discuss: 'Parler de votre expédition', mapNote: 'Carte illustrative · disponibilité à confirmer pour chaque expédition', portugal: 'Portugal', europe: 'Europe' },
    pages: {
      'about-us': { hero: ['À propos de Trevola', 'Un partenaire routier', 'à la coordination claire.', 'Une communication claire et une planification pratique entre le Portugal et l’Europe.'], heading: ['Un partenaire accessible', 'Le transport routier,', 'en toute clarté.'], paragraphs: ['Trevola Logistics coordonne le transport routier international entre le Portugal et des destinations européennes.', 'Nous suivons les détails utiles à une expédition fluide : marchandise, itinéraire, délais et communication.', 'Chaque demande est différente. Nous étudions des options adaptées et restons disponibles du départ à la livraison.'], cards: [{ title: 'Comprendre le besoin', text: 'Nous commençons par la marchandise, le départ, la destination, le délai et les exigences de manutention.' }, { title: 'Coordonner le plan', text: 'Nous étudions des options routières et confirmons les détails du transport demandé.' }, { title: 'Rester en contact', text: 'Nous restons votre interlocuteur pendant la coordination de l’expédition.' }] },
      services: { hero: ['Transport routier', 'La bonne solution', 'pour chaque envoi.', 'Des options flexibles adaptées à la marchandise, au trajet et aux délais.'], heading: ['Solutions routières', 'Un transport adapté', 'à votre marchandise.'], paragraphs: ['Choisissez un service pour commencer. Disponibilité et organisation sont confirmées pour chaque expédition.'], cards: [{ icon: 'truck', title: 'Chargement complet (FTL)', text: 'Capacité dédiée aux chargements complets, planifiée selon la route, la marchandise et le délai souhaité.' }, { icon: 'boxes', title: 'Chargement partiel (LTL)', text: 'Des solutions de groupage pour les expéditions ne nécessitant pas un véhicule complet.' }, { icon: 'clock', title: 'Transport express', text: 'Transport urgent coordonné avec une communication claire et le suivi des délais convenus.' }, { icon: 'route', title: 'Transport dédié', text: 'Un plan adapté aux besoins précis de votre expédition.' }, { icon: 'globe', title: 'Transport routier européen', text: 'Coordination du transport international entre le Portugal et des destinations européennes.' }, { icon: 'shield', title: 'Coordination logistique', text: 'Un interlocuteur direct de l’enlèvement à la livraison.' }] },
      fleet: { hero: ['Flotte et réseau', 'Une capacité qui fait', 'avancer votre activité.', 'Un transport coordonné selon les besoins de chaque expédition.'], heading: ['Flotte et réseau de transport', 'Une capacité flexible.', 'Un contact unique.'], paragraphs: ['Trevola coordonne des capacités de transport adaptées à chaque expédition.', 'Le véhicule, l’itinéraire, le chargement et les délais sont étudiés pour chaque demande. La solution disponible est confirmée avant réservation.', 'Trevola Logistics est présentée comme coordinatrice de transport et ne revendique pas la propriété des véhicules illustrés.'], cards: [{ title: 'Profil de l’envoi', text: 'Nous examinons dimensions, poids, nature de la marchandise et lieux de collecte et livraison.' }, { title: 'Option de transport', text: 'Les capacités et itinéraires adaptés sont étudiés selon les besoins.' }, { title: 'Détails confirmés', text: 'Les délais et modalités sont confirmés avant le transport.' }] },
      industries: { hero: ['Secteurs accompagnés', 'Un transport adapté', 'à votre secteur.', 'Une approche réfléchie de la marchandise, du trajet et des délais.'], heading: ['Secteurs accompagnés', 'Du transport routier pour', 'différents besoins.'], paragraphs: ['Chaque secteur a ses exigences. Nous étudions la marchandise, l’itinéraire et les délais pour proposer une solution adaptée.'], cards: [{ icon: 'car', title: 'Automobile', text: 'Composants et marchandises pour les chaînes d’approvisionnement automobiles.' }, { icon: 'wheat', title: 'Agriculture', text: 'Planification du transport de produits et matériaux agricoles.' }, { icon: 'industry', title: 'Équipements industriels', text: 'Coordination de machines, pièces et équipements industriels.' }, { icon: 'cart', title: 'Commerce de détail', text: 'Transport pour la distribution, le réapprovisionnement et les stocks.' }, { icon: 'food', title: 'Alimentation et boissons', text: 'Coordination des marchandises alimentaires selon les besoins de l’envoi.' }, { icon: 'package', title: 'Commerce en ligne', text: 'Options de transport pour les marchandises du commerce en ligne.' }], note: 'Ces catégories illustrent des besoins généraux. Les exigences spéciales, marchandises réglementées et équipements doivent être confirmés avant réservation.' },
      contact: { hero: ['Contact', 'Commençons', 'la conversation.', 'Parlez à Trevola Logistics de vos besoins de transport routier.'], heading: ['Contacter Trevola Logistics', 'Parlons de', 'votre prochaine expédition.'], paragraphs: ['Notre équipe échange sur le transport routier entre le Portugal et les destinations européennes.', 'Indiquez l’origine, la destination, la marchandise et le délai souhaité. Nous vous expliquons les prochaines étapes.'] },
    },
    quote: { intro: 'Partagez les détails de la marchandise et du trajet. Notre équipe pourra étudier une solution adaptée.', fieldsTitle: 'Que souhaitez-vous transporter ?', requiredNote: 'Les champs suivis de * sont obligatoires.', labels: { company: 'Entreprise', contact: 'Personne à contacter', email: 'E-mail', phone: 'Téléphone', pickupCountry: 'Pays de collecte', pickupCity: 'Ville de collecte', deliveryCountry: 'Pays de livraison', deliveryCity: 'Ville de livraison', transport: 'Type de transport', pallets: 'Nombre de palettes', cargo: 'Description de la marchandise', weight: 'Poids (kg)', volume: 'Volume (m³)', loadingDate: 'Date de chargement souhaitée', additional: 'Informations complémentaires' }, select: 'Choisir le type de transport', errors: { required: 'Veuillez remplir ce champ.', email: 'Saisissez une adresse e-mail valide.', minimum: 'Saisissez un nombre positif valide.', date: 'Choisissez aujourd’hui ou une date ultérieure.' }, loading: 'Envoi de la demande…', success: 'Merci. Votre demande de devis a été envoyée à Trevola Logistics.', notConfigured: 'L’envoi en ligne n’est pas encore configuré. Rien n’a été envoyé. Écrivez à info@trevolalogistics.com.', genericError: 'La demande n’a pas pu être envoyée. Réessayez ou écrivez à info@trevolalogistics.com.' },
    legal: {
      'privacy-policy': { title: 'Politique de confidentialité', sections: [{ title: 'Responsable du traitement', text: 'Le site est exploité sous la marque Trevola Logistics. Avant publication, l’exploitant doit indiquer ici sa raison sociale complète et son adresse postale. Questions : info@trevolalogistics.com.' }, { title: 'Données et finalités', text: 'Lorsque les demandes de devis seront activées, les informations du formulaire (entreprise, contact, trajet, marchandise et date) serviront à répondre à la demande et préparer une proposition. L’hébergeur peut traiter des journaux techniques de sécurité.' }, { title: 'Base et destinataires', text: 'Les données de demande sont traitées pour des démarches précontractuelles sollicitées. Une fois l’intégration e-mail activée, le message sera transmis à Trevola Logistics via le prestataire configuré. Le prestataire, ses conditions de traitement et les garanties de transfert éventuelles doivent être vérifiés avant activation.' }, { title: 'Conservation et droits', text: 'Avant l’activation, l’entreprise doit définir et publier une durée de conservation adaptée à ses besoins opérationnels et légaux. Selon les règles applicables, vous pouvez demander l’accès, la rectification, l’effacement ou la limitation, vous opposer au traitement et déposer une plainte auprès de la CNPD. Contact : info@trevolalogistics.com.' }, { title: 'Mise à jour', text: 'Ce modèle doit être adapté à l’entité juridique, à l’hébergement, au prestataire e-mail, à la durée de conservation et aux pratiques réelles. Actualisez la date après vérification.' }], note: 'Modèle à compléter par l’exploitant · Révisé le 4 octobre 2026' },
      cookies: { title: 'Politique relative aux cookies', sections: [{ title: 'Stockage utilisé actuellement', text: 'Le site actuel ne charge aucun outil publicitaire ou analytique. Il mémorise la langue choisie dans le stockage local du navigateur. Cette préférence fonctionnelle n’est utilisée ni pour la publicité ni pour le profilage.' }, { title: 'Technologies nécessaires', text: 'L’hébergeur peut utiliser des mécanismes techniques nécessaires à la diffusion et à la sécurité du site. L’exploitant doit vérifier ses pratiques avant publication.' }, { title: 'Vos choix', text: 'Vous pouvez supprimer la préférence linguistique dans les paramètres de données du site de votre navigateur. Si des outils facultatifs d’analyse ou de marketing sont ajoutés, cet avis et le mécanisme de consentement doivent être révisés avant leur activation.' }, { title: 'Contact', text: 'Pour toute question sur cet avis ou le stockage, écrivez à info@trevolalogistics.com.' }], note: 'Cet avis décrit le code actuel et doit être vérifié avec l’hébergement final.' },
      terms: { title: 'Conditions générales', sections: [{ title: 'Informations du site', text: 'Ce site présente des informations générales sur Trevola Logistics et la coordination du transport routier. Son contenu n’est pas une offre ferme et ne confirme pas la disponibilité d’un itinéraire, d’un véhicule ou d’une date.' }, { title: 'Devis et réservations', text: 'Une demande de devis est une simple demande d’information. Le périmètre, le prix, la capacité, les délais, la manutention et les conditions contractuelles doivent être confirmés par écrit avant réservation.' }, { title: 'Exactitude et disponibilité', text: 'Les informations, cartes et images illustratives sont fournies à titre indicatif. Les itinéraires et modalités sont confirmés pour chaque expédition.' }, { title: 'Propriété intellectuelle et contact', text: 'Les textes, la mise en page et les éléments de marque ne peuvent être copiés ou réutilisés sans l’autorisation des ayants droit. Contact : info@trevolalogistics.com.' }, { title: 'Exploitant et droit applicable', text: 'L’exploitant doit ajouter sa raison sociale, son adresse et les détails relatifs au droit et à la juridiction applicables avant publication. Ce modèle doit être vérifié pour l’activité finale.' }], note: 'Modèle · Compléter les coordonnées de l’entreprise et la juridiction avant publication.' },
    },
    careers: { emptyTitle: 'Aucun poste à pourvoir actuellement', emptyText: 'Aucune offre n’est publiée pour le moment. Pour vous présenter en vue de futures opportunités, contactez notre équipe par e-mail.', button: 'Contacter Trevola Logistics' },
    news: { emptyTitle: 'Aucune actualité publiée', emptyText: 'Aucun article n’est disponible pour le moment. Revenez plus tard pour les nouvelles de l’entreprise et de la logistique.' },
    cta: { eyebrow: 'Prêt à avancer ?', title: 'Prêt à transporter votre marchandise ?', text: 'Nos experts logistiques trouveront la meilleure solution de transport pour votre entreprise.', quote: 'Demander un devis', contact: 'Nous contacter' },
    seo: {
      home: ['Trevola Logistics | Transport routier européen', 'Transport routier international entre le Portugal et les destinations européennes, coordonné par Trevola Logistics.'],
      'about-us': ['À propos | Trevola Logistics', 'Découvrez Trevola Logistics, partenaire portugais de coordination du transport routier en Europe.'],
      services: ['Services routiers | Trevola Logistics', 'Solutions FTL, LTL, express et transport dédié pour vos expéditions européennes.'],
      fleet: ['Flotte et réseau | Trevola Logistics', 'Capacité de transport coordonnée selon la marchandise, l’itinéraire et les délais.'],
      industries: ['Secteurs | Trevola Logistics', 'Coordination routière pour l’automobile, l’agriculture, le commerce, l’alimentation et d’autres secteurs.'],
      'request-a-quote': ['Demander un devis | Trevola Logistics', 'Partagez le trajet et les caractéristiques de votre marchandise pour demander un devis.'],
      contact: ['Contact | Trevola Logistics', 'Contactez Trevola Logistics au Portugal pour le transport routier international.'],
      'privacy-policy': ['Confidentialité | Trevola Logistics', 'Comment Trevola Logistics traite les informations du site et les demandes de transport.'],
      cookies: ['Cookies | Trevola Logistics', 'Informations sur les cookies et le stockage du navigateur utilisés par le site.'],
      terms: ['Conditions générales | Trevola Logistics', 'Conditions du site et des demandes de coordination du transport routier.'],
      careers: ['Carrières | Trevola Logistics', 'Opportunités et coordonnées de Trevola Logistics.'],
      news: ['Actualités | Trevola Logistics', 'Actualités de l’entreprise et du secteur logistique par Trevola Logistics.'],
    },
  },
}
